# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Ettore Atalan <atalanttore@googlemail.com>, 2015
# psyca, 2015-2016
# psyca, 2015
msgid ""
msgstr ""
"Project-Id-Version: fwbackups\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-01-07 01:37-0800\n"
"PO-Revision-Date: 2017-09-22 11:45+0000\n"
"Last-Translator: psyca\n"
"Language-Team: German (http://www.transifex.com/Magic/fwbackups/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: data/com.diffingo.fwbackups.desktop.in:3 fwbackups/ui/gtk/main.ui:22
#: fwbackups/ui/__init__.py:71
msgid "fwbackups"
msgstr "fwbackups"

#: data/com.diffingo.fwbackups.desktop.in:4
msgid "Backup or restore your files"
msgstr ""

#: data/com.diffingo.fwbackups.desktop.in:6
msgid "backup;archive;archiving;"
msgstr ""

#: data/com.diffingo.fwbackups.metainfo.xml.in:7 fwbackups/ui/__init__.py:848
msgid "A feature-rich user backup program"
msgstr ""

#: fwbackups/ui/gtk/BugReport.ui:69
msgid "<span size=\"larger\" weight=\"bold\">Sorry!</span>"
msgstr ""

#: fwbackups/ui/gtk/BugReport.ui:81
msgid ""
"fwbackups has run into an unexpected error. You may continue using the "
"program, however it is recommended you quit and open fwbackups again."
msgstr ""

#: fwbackups/ui/gtk/BugReport.ui:117
msgid "_Details"
msgstr "_Details"

#: fwbackups/ui/gtk/backupset.ui:11
msgid "Configure Set"
msgstr "Satz konfigurieren"

#: fwbackups/ui/gtk/backupset.ui:174
msgid "Paths"
msgstr "Pfade"

#: fwbackups/ui/gtk/backupset.ui:203
msgid "Destination Type:"
msgstr "Zieltyp:"

#: fwbackups/ui/gtk/backupset.ui:267 fwbackups/ui/gtk/backupset.ui:326
#: fwbackups/ui/gtk/main.ui:600 fwbackups/ui/gtk/main.ui:685
#: fwbackups/ui/gtk/restore.ui:202
msgid "Folder:"
msgstr "Ordner:"

#: fwbackups/ui/gtk/backupset.ui:294 fwbackups/ui/gtk/main.ui:628
msgid "/folder"
msgstr "/verzeichnis"

#: fwbackups/ui/gtk/backupset.ui:337 fwbackups/ui/gtk/main.ui:649
#: fwbackups/ui/gtk/restore.ui:275
msgid "Host:"
msgstr "Host:"

#: fwbackups/ui/gtk/backupset.ui:349 fwbackups/ui/gtk/main.ui:661
#: fwbackups/ui/gtk/restore.ui:287
msgid "Username:"
msgstr "Benutzername:"

#: fwbackups/ui/gtk/backupset.ui:361 fwbackups/ui/gtk/main.ui:673
#: fwbackups/ui/gtk/restore.ui:299
msgid "Password:"
msgstr "Passwort:"

#: fwbackups/ui/gtk/backupset.ui:378 fwbackups/ui/gtk/main.ui:701
msgid "_Test Settings"
msgstr "_Überprüfe Eins_tellungen"

#: fwbackups/ui/gtk/backupset.ui:401 fwbackups/ui/gtk/main.ui:725
#: fwbackups/ui/gtk/restore.ui:364
msgid "Hide password"
msgstr "Passwort verstecken"

#: fwbackups/ui/gtk/backupset.ui:449 fwbackups/ui/gtk/main.ui:783
#: fwbackups/ui/gtk/restore.ui:400
msgid "Port:"
msgstr "Port:"

#: fwbackups/ui/gtk/backupset.ui:500
msgid "Destination"
msgstr "Ziel"

#: fwbackups/ui/gtk/backupset.ui:527
msgid ""
"Use the same syntax a crontab does to enter your settings. To obtain "
"examples and more information on crontab syntax, click 'Help'."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:620
msgid ""
"No field verification is performed on a manual field to test if the input is "
"valid. Please make sure there are no errors."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:687
msgid "Manual Configuration"
msgstr "Manuelle Konfiguration"

#: fwbackups/ui/gtk/backupset.ui:718
msgid "All Months"
msgstr "Alle Monate"

#: fwbackups/ui/gtk/backupset.ui:730
msgid "Only during:"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:741 fwbackups/ui/gtk/backupset.ui:901
msgid "From:"
msgstr "Von:"

#: fwbackups/ui/gtk/backupset.ui:806 fwbackups/ui/gtk/backupset.ui:958
msgid "To:"
msgstr "Bis:"

#: fwbackups/ui/gtk/backupset.ui:851
msgid "<b>Months</b>"
msgstr "<b>Monate</b>"

#: fwbackups/ui/gtk/backupset.ui:877
msgid "Only on:"
msgstr "Nur an:"

#: fwbackups/ui/gtk/backupset.ui:889
msgid "All days of the week"
msgstr "Alle Tage in der Woche"

#: fwbackups/ui/gtk/backupset.ui:998
msgid "<b>Days of the week</b>"
msgstr "<b>Tage in der Woche</b>"

#: fwbackups/ui/gtk/backupset.ui:1024
msgid "At:"
msgstr "Um:"

#: fwbackups/ui/gtk/backupset.ui:1035
msgid "All Hours"
msgstr "Alle Stunden"

#: fwbackups/ui/gtk/backupset.ui:1087
msgid "<b>Hours</b>"
msgstr "<b>Stunden</b>"

#: fwbackups/ui/gtk/backupset.ui:1111
msgid "Only at:"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1122
msgid "All Minutes"
msgstr "Alle Minuten"

#: fwbackups/ui/gtk/backupset.ui:1153
msgid "<b>Minute</b>"
msgstr "<b>Minute</b>"

#: fwbackups/ui/gtk/backupset.ui:1171
msgid "Easy Configuration"
msgstr "Einfache Konfiguration"

#: fwbackups/ui/gtk/backupset.ui:1185
msgid ""
"Your backup will run whenever <b>all</b> of the criteria below match the "
"system time and date."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1210
msgid "Times"
msgstr "Zeiten"

#: fwbackups/ui/gtk/backupset.ui:1236 fwbackups/ui/gtk/main.ui:856
msgid "Archive (files and folders are packed into a tar archive)"
msgstr "Archiv (Dateien und Verzeichnisse werden in ein tar Archiv gepackt)"

#: fwbackups/ui/gtk/backupset.ui:1250 fwbackups/ui/gtk/main.ui:870
msgid "Direct copy of the files and folders"
msgstr "Direkte Kopie der Dateien und Verzeichnisse"

#: fwbackups/ui/gtk/backupset.ui:1276 fwbackups/ui/gtk/main.ui:888
msgid "Compress archive using"
msgstr "Komprimiere Archiv mit"

#: fwbackups/ui/gtk/backupset.ui:1303
msgid "Backups are incremental"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1320 fwbackups/ui/gtk/main.ui:913
msgid "<b>Backup Format</b>"
msgstr "<b>Sicherungsformat</b>"

#: fwbackups/ui/gtk/backupset.ui:1339
msgid "Set is enabled"
msgstr "Satz ist aktiviert"

#: fwbackups/ui/gtk/backupset.ui:1351
msgid "Include subfolders"
msgstr "Unterverzeichnisse einbeziehen"

#: fwbackups/ui/gtk/backupset.ui:1364 fwbackups/ui/gtk/main.ui:971
msgid "Print disk geometry information to a file"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1377 fwbackups/ui/gtk/main.ui:958
msgid "Print installed packages to a text file"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1389 fwbackups/ui/gtk/main.ui:983
msgid "Include hidden files"
msgstr "Versteckte Dateien miteinbeziehen"

#: fwbackups/ui/gtk/backupset.ui:1401 fwbackups/ui/gtk/main.ui:995
msgid "Handle sparse files efficiently"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1412 fwbackups/ui/gtk/main.ui:1006
msgid "Follow links"
msgstr "Folge Links"

#: fwbackups/ui/gtk/backupset.ui:1425 fwbackups/ui/gtk/backupset.ui:1485
#: fwbackups/ui/gtk/main.ui:1019
msgid "<b>Backup Options</b>"
msgstr "<b>Sicherungsoptionen</b>"

#: fwbackups/ui/gtk/backupset.ui:1442
msgid "Number of old backups to keep:"
msgstr "Anzahl an alten Backups die behalten werden sollen:"

#: fwbackups/ui/gtk/backupset.ui:1471
#, fuzzy
msgid ""
"A value of  '0' makes a new backup always replace an older one. This option "
"is unavailable with incremental backups."
msgstr ""
"<i>Tipp:</i>0<i> bedeutet das eine neue Sicherung immer die alte ersetzt.\n"
"Diese Option ist bei inkrementellen Sicherungen nicht verfügbar.</i>"

#: fwbackups/ui/gtk/backupset.ui:1507
msgid "Options (Simple)"
msgstr "Optionen (Einfach)"

#: fwbackups/ui/gtk/backupset.ui:1557
msgid "Command to run before backup:"
msgstr "Befehl der vor der Sicherung ausgeführt werden soll:"

#: fwbackups/ui/gtk/backupset.ui:1568
msgid "Command to run after backup:"
msgstr "Befehl der nach der Sicherung ausgeführt werden soll:"

#: fwbackups/ui/gtk/backupset.ui:1579 fwbackups/ui/gtk/main.ui:1083
msgid "Nice value of backup process:"
msgstr "Nice Wert des Sicherungsprozesses:"

#: fwbackups/ui/gtk/backupset.ui:1590
msgid ""
"Exclude from backup:\n"
" (newline separated)"
msgstr ""
"Von der Sicherung ausschließen:\n"
"(getrennt durch neue Zeilen)"

#: fwbackups/ui/gtk/backupset.ui:1636
msgid ""
"The following tokens may be used in the commands:\n"
"[destination], [set], [date], [backup], [remote_host], [remote_port], "
"[remote_username], [remote_password]\n"
"\n"
"For a description of each, see the user manual."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1666
msgid "Options (Advanced)"
msgstr "Optionen (Erweitert)"

#: fwbackups/ui/gtk/backupset.ui:1695
msgid "<b>Name:</b>"
msgstr "<b>Name:</b>"

#: fwbackups/ui/gtk/confirm_dia.ui:36 fwbackups/ui/gtk/error_dia.ui:36
#: fwbackups/ui/gtk/info_dia.ui:35 fwbackups/ui/gtk/warning_dia.ui:39
msgid ""
"<span size=\"larger\" weight=\"bold\">Primary text</span>\n"
"\n"
"Secondary text"
msgstr ""

#: fwbackups/ui/gtk/confirm_dia.ui:49 fwbackups/ui/gtk/info_dia.ui:47
#: fwbackups/ui/gtk/warning_dia.ui:52
msgid "Don't show me this message again"
msgstr "Diese Meldung nicht erneut anzeigen"

#: fwbackups/ui/gtk/export_dia.ui:10 fwbackups/ui/__init__.py:692
msgid "Export Sets"
msgstr "Exportiere Sätze"

#: fwbackups/ui/gtk/export_dia.ui:44
msgid "<span size=\"larger\" weight=\"bold\">Export Sets</span>"
msgstr "<span size=\"larger\" weight=\"bold\">Sätze exportieren</span>"

#: fwbackups/ui/gtk/export_dia.ui:57
msgid "Select the set you would like to export."
msgstr "Wähle den Satz, den Sie exportieren möchten."

#: fwbackups/ui/gtk/export_dia.ui:96
msgid "_Export"
msgstr "_Exportieren"

#: fwbackups/ui/gtk/main.ui:63
msgid "To start, click one of the buttons on the above or use the menus."
msgstr ""

#: fwbackups/ui/gtk/main.ui:74
#, fuzzy
msgid ""
"Please do not forget to check your fwbackups log regularly to be informed "
"about any errors and/or failed backup runs."
msgstr ""
"Bitte vergessen Sie nicht regelmäßig die Logs von fwbackups zu überprüfen, "
"um über\n"
"Fehler und/oder fehlgeschlagene Sicherungen informiert zu sein."

#: fwbackups/ui/gtk/main.ui:88
msgid "<b>Welcome</b>"
msgstr "<b>Willkommen</b>"

#: fwbackups/ui/gtk/main.ui:113 fwbackups/ui/gtk/main.ui:124
msgid "<i>Not Loaded</i>"
msgstr "<i>Nicht geladen</i>"

#: fwbackups/ui/gtk/main.ui:136
msgid "Total backup sets:"
msgstr "Sicherungssätze insgesamt:"

#: fwbackups/ui/gtk/main.ui:147
msgid "Failed backup runs:"
msgstr ""

#: fwbackups/ui/gtk/main.ui:162
msgid "<b>Status</b>"
msgstr "<b>Status</b>"

#: fwbackups/ui/gtk/main.ui:181
msgid "Overview"
msgstr "Übersicht"

#: fwbackups/ui/gtk/main.ui:376 fwbackups/ui/gtk/main.ui:1119
#: fwbackups/ui/gtk/restore.ui:581
msgid "Status:"
msgstr "Status:"

#: fwbackups/ui/gtk/main.ui:386 fwbackups/ui/gtk/main.ui:1130
msgid "Backup progress:"
msgstr "Fortschritt der Sicherung:"

#: fwbackups/ui/gtk/main.ui:400
#, fuzzy
msgid "Backups Sets"
msgstr "Sicherungssätze"

#: fwbackups/ui/gtk/main.ui:820
msgid "Destination type:"
msgstr "Zieltyp:"

#: fwbackups/ui/gtk/main.ui:932
msgid "Enabled"
msgstr "Aktiviert"

#: fwbackups/ui/gtk/main.ui:945
msgid "Recursive"
msgstr "Rekursiv"

#: fwbackups/ui/gtk/main.ui:1071
#, fuzzy
msgid "Exclude from backup (newline separated):"
msgstr ""
"Von der Sicherung ausschließen:\n"
"(getrennt durch neue Zeilen)"

#: fwbackups/ui/gtk/main.ui:1095
msgid "<b>Advanced Options</b>"
msgstr "<b>Erweiterte Optionen</b>"

#: fwbackups/ui/gtk/main.ui:1170 fwbackups/ui/gtk/restore.ui:592
msgid "%s"
msgstr "%s"

#: fwbackups/ui/gtk/main.ui:1266
msgid "One-Time Backup"
msgstr "Einmalige Sicherung"

#: fwbackups/ui/gtk/main.ui:1342
msgid "_Save to File"
msgstr "In Datei _speichern"

#: fwbackups/ui/gtk/main.ui:1390
msgid "Log Viewer"
msgstr "Log-Betrachter"

#: fwbackups/ui/gtk/main.ui:1524
msgid "Restore"
msgstr "Wiederherstellen"

#: fwbackups/ui/gtk/preferences.ui:29
#, fuzzy
msgid "Enable debug log messages"
msgstr "Vorherige Protokollmeldungen"

#: fwbackups/ui/gtk/preferences.ui:75
msgid "Override temporary directory:"
msgstr ""

#: fwbackups/ui/gtk/preferences.ui:94
#, fuzzy
msgid "Enable notifications"
msgstr "Be_nachrichtigungen anzeigen"

#: fwbackups/ui/gtk/preferences.ui:107
#, fuzzy
msgid "<b>Options</b>"
msgstr "<b>Versch. Optionen</b>"

#: fwbackups/ui/gtk/preferences.ui:141
msgid "Click to reset \"Don't show me again\" messages"
msgstr ""

#: fwbackups/ui/gtk/preferences.ui:174
msgid "Preferences"
msgstr "Einstellungen"

#: fwbackups/ui/gtk/restore.ui:63
msgid "Set:"
msgstr "Satz:"

#: fwbackups/ui/gtk/restore.ui:73
msgid "Date:"
msgstr "Datum:"

#: fwbackups/ui/gtk/restore.ui:147
msgid "Archive:"
msgstr "Archiv:"

#: fwbackups/ui/gtk/restore.ui:242
msgid "/"
msgstr "/"

#: fwbackups/ui/gtk/restore.ui:311
msgid "Location:"
msgstr "Ort:"

#: fwbackups/ui/gtk/restore.ui:326
msgid "Test Settings"
msgstr "Überprüfe Einstellungen"

#: fwbackups/ui/gtk/restore.ui:349
#, fuzzy
msgid ""
"Note: fwbackups will copy the remote backup to the disk first, then unpack "
"it. Please ensure enough disk space is available."
msgstr ""
"<i>Hinweis: fwbackups wird zuerst die entfernte Sicherung auf das Laufwerk "
"kopieren und danach entpacken.\n"
"Bitte vergewissern Sie sich, dass genügend Speicherplatz verfügbar ist.</i>"

#: fwbackups/ui/gtk/restore.ui:449
msgid "Source type:"
msgstr "Quellentyp:"

#: fwbackups/ui/gtk/restore.ui:461
msgid "Restore to:"
msgstr "Wiederherstellen nach:"

#: fwbackups/ui/gtk/restore.ui:514
msgid ""
"Tip: entering '/' or selecting 'File System' will restore files to their "
"original locations."
msgstr ""

#: fwbackups/ui/gtk/restore.ui:540
msgid "Restore Progress:"
msgstr "Fortschritt der Wiederherstellung:"

#: fwbackups/ui/gtk/restore.ui:658
msgid "_Finish"
msgstr "_Fertig"

#: fwbackups/ui/gtk/restore.ui:671
msgid "Restore Files"
msgstr "Dateien wiederherstellen"

#: fwbackups/config.py:58
#, python-format
msgid "Could not create configuration folder `%s':"
msgstr "Konnte das Konfigurationsverzeichnis `%s' nicht erstellen:"

#: fwbackups/config.py:65
#, python-format
msgid "You do not have read and write permissions on folder `%s'."
msgstr "Sie haben keine Lese- und Schreibrechte auf das Verzeichnis `%s'."

#: fwbackups/config.py:125
#, python-format
msgid "Key %s of is not a dictionary of options"
msgstr ""

#: fwbackups/config.py:341
#, python-format
msgid "Set '%s' failed to pass section validation"
msgstr ""

#: fwbackups/config.py:344
#, python-format
msgid "'%(a)s' is not a set configuration file."
msgstr ""

#: fwbackups/config.py:348
#, python-format
msgid ""
"Configuration section 'General' in the set configuration '%s' failed to "
"validate"
msgstr ""

#: fwbackups/config.py:351
#, python-format
msgid ""
"Configuration section 'Times' in the set configuration '%s' failed to "
"validate"
msgstr ""

#: fwbackups/config.py:364
#, python-format
msgid "Unknown option key '%(a)s' present in set configuration '%(b)s'"
msgstr ""

#: fwbackups/config.py:369
#, python-format
msgid ""
"Configuration section 'Options' in set configuration '%(a)s' failed to "
"validate: Missing options '%(b)s'"
msgstr ""

#: fwbackups/config.py:504
msgid "One-time configuration failed to pass section validation"
msgstr ""

#: fwbackups/config.py:507
#, python-format
msgid "'%(a)s' is not a one-time configuration file."
msgstr ""

#: fwbackups/config.py:511
msgid ""
"Configuration section 'General' in the one-time configuration file failed to "
"validate"
msgstr ""

#: fwbackups/config.py:523
#, python-format
msgid "Unknown option key '%s' present in one-time backup configuration file"
msgstr ""

#: fwbackups/config.py:528
#, python-format
msgid ""
"Configuration section 'Options' in the one-time backup configuration file "
"failed to validate: Missing options '%s'"
msgstr ""

#: fwbackups/config.py:632
msgid "Restore configuration failed to pass section validation"
msgstr ""

#: fwbackups/config.py:635
#, python-format
msgid "'%(a)s' is not a restore configuration file."
msgstr ""

#: fwbackups/config.py:639
msgid ""
"Configuration section 'General' in the restore configuration file failed to "
"validate"
msgstr ""

#: fwbackups/config.py:649
#, python-format
msgid "Unknown option key '%s' present in restore configuration file"
msgstr ""

#: fwbackups/config.py:654
#, python-format
msgid ""
"Configuration section 'Options' in the restore configuration file failed to "
"validate: Missing options '%s'"
msgstr ""

#: fwbackups/config.py:738
msgid "Preferences failed to pass section validation"
msgstr ""

#: fwbackups/config.py:741
#, python-brace-format
msgid "'{constants.PREFSLOC}' is not a fwbackups preferences file."
msgstr ""

#: fwbackups/config.py:745
msgid ""
"Configuration section 'General' in the preferences file failed to validate"
msgstr ""

#: fwbackups/config.py:755
#, python-format
msgid "Unknown option key '%s' present in preferences file"
msgstr ""

#: fwbackups/config.py:760
#, python-format
msgid ""
"Configuration section 'Options' in the preferences file failed to validate: "
"Missing options '%s'"
msgstr ""

#: fwbackups/fwlogger.py:73
#, python-format
msgid "Could not set up the logger: %s"
msgstr ""

#: fwbackups/operations/__init__.py:62
msgid "Canceling the current operation!"
msgstr "Den aktuellen Vorgang abbrechen!"

#: fwbackups/operations/__init__.py:66
#, python-format
msgid "Stopping process with ID %s"
msgstr "Stoppe Prozess mit der ID %s"

#: fwbackups/operations/__init__.py:69
#, fuzzy, python-format
msgid "Could not stop process %s: %s"
msgstr "Konnte den Thread %s nicht schließen!"

#: fwbackups/operations/__init__.py:77
msgid "The operation has been cancelled."
msgstr "Der Vorgang wurde abgebrochen."

#: fwbackups/operations/__init__.py:90
#, python-format
msgid "Error handling file `%s'"
msgstr ""

#: fwbackups/operations/__init__.py:91
#, python-format
msgid ""
"Output:\n"
"%s"
msgstr ""
"Ausgabe:\n"
"%s"

#: fwbackups/operations/__init__.py:96
#, python-format
msgid "Destination folder `%s' exists"
msgstr "Zielordner `%s' vorhanden"

#: fwbackups/operations/__init__.py:101
#, python-format
msgid "Created destination folder `%s'"
msgstr "Zielordner `%s' erstellt"

#: fwbackups/operations/__init__.py:103
#, python-format
msgid "The destination folder `%(a)s' could not be created: %(b)s"
msgstr "Der Zielordner `%(a)s' konnte nicht erstellt werden: %(b)s"

#: fwbackups/operations/__init__.py:107
#, python-format
msgid ""
"You do not have read and write permissions on the destination `%s' - if you "
"backed up system files, this operation may fail."
msgstr ""

#: fwbackups/operations/backup.py:86
msgid "rpm - Package list"
msgstr "rpm - Paketliste"

#: fwbackups/operations/backup.py:105
msgid "Pacman - Package list"
msgstr "Pacman - Paketliste"

#: fwbackups/operations/backup.py:111
msgid "dpkg - Package list"
msgstr "dpkg - Paketliste"

#: fwbackups/operations/backup.py:121
msgid "Disk Information"
msgstr "Laufwerksinformationen"

#: fwbackups/operations/backup.py:189
#, python-format
msgid "Attempting to connect to server %s..."
msgstr "Versuche mit dem Server %s zu verbinden..."

#: fwbackups/operations/backup.py:200
msgid "Attempt to connect succeeded."
msgstr "Der Verbindungsversuch war erfolgreich."

#: fwbackups/operations/backup.py:203
msgid ""
"The backup destination was either not found or it cannot be written to due "
"to insufficient permissions."
msgstr ""
"Das Sicherungsziel wurde nicht gefunden oder es kann aufgrund von fehlenden "
"Berechtigungen nicht beschrieben werden."

#: fwbackups/operations/backup.py:207 fwbackups/operations/restore.py:93
msgid ""
"A connection was established, but authentication failed. Please verify the "
"username and password and try again."
msgstr ""
"Eine Verbindung wurde hergestellt, jedoch ist die Authentifizierung "
"fehlgeschlagen. Bitte überprüfen Sie den Benutzernamen und das Passwort und "
"versuchen es erneut."

#: fwbackups/operations/backup.py:212 fwbackups/operations/restore.py:98
#, python-format
msgid ""
"A connection to the server could not be established.\n"
"Error %(a)s: %(b)s"
msgstr ""
"Eine Verbindung zum Server konnte nicht hergestellt werden.\n"
"Fehler %(a)s: %(b)s"

#: fwbackups/operations/backup.py:217 fwbackups/operations/restore.py:103
msgid ""
"A connection to the server has timed out. Please verify your settings and "
"try again."
msgstr ""
"Zeitüberschreitung bei der Verbindung zum Server. Bitte überprüfen Sie die "
"Einstellungen und versche es erneut."

#: fwbackups/operations/backup.py:221 fwbackups/operations/restore.py:107
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s"
msgstr ""
"Eine Verbindung zum Server konnte aufgrund eines Fehlers nicht aufgebaut "
"werden: %s"

#: fwbackups/operations/backup.py:239 fwbackups/operations/backup.py:277
#: fwbackups/operations/backup.py:320
#, python-format
msgid ""
"Using %s on Windows: Cancel function will only take effect after a path has "
"been completed."
msgstr ""

#. let's deal with real paths
#: fwbackups/operations/backup.py:245 fwbackups/operations/backup.py:283
#: fwbackups/operations/backup.py:293 fwbackups/operations/backup.py:326
#: fwbackups/operations/backup.py:336 fwbackups/operations/backup.py:372
#: fwbackups/operations/backup.py:384
#, python-format
msgid "Backing up path %(a)i/%(b)i: %(c)s"
msgstr "Sichere Pfad %(a)i/%(b)i: %(c)s"

#: fwbackups/operations/backup.py:253
#, python-format
msgid "Running command: nice -n %(a)i %(b)s '%(c)s'"
msgstr ""

#: fwbackups/operations/backup.py:256 fwbackups/operations/backup.py:298
#: fwbackups/operations/backup.py:341 fwbackups/operations/backup.py:391
#: fwbackups/operations/backup.py:598
#, python-format
msgid "Starting subprocess with PID %s"
msgstr "Starte Subprozess mit der PID %s"

#: fwbackups/operations/backup.py:267 fwbackups/operations/backup.py:310
#: fwbackups/operations/backup.py:353 fwbackups/operations/backup.py:403
#, python-format
msgid "Subprocess with PID %(a)s exited with status %(b)s"
msgstr "Subprozess mit der PID %(a)s wurde mit dem Status %(b)s beendet"

#: fwbackups/operations/backup.py:272 fwbackups/operations/backup.py:315
#: fwbackups/operations/backup.py:358 fwbackups/operations/backup.py:409
#: fwbackups/operations/backup.py:613
#, python-format
msgid "Process exited with status %(a)s. Errors: %(b)s"
msgstr "Prozess beendet mit dem Status %(a)s. Fehler: %(b)s"

#: fwbackups/operations/backup.py:285 fwbackups/operations/backup.py:328
#, python-format
msgid "Adding path `%s' to the archive"
msgstr "Füge Pfad `%s' zum Archiv hinzu"

#: fwbackups/operations/backup.py:292 fwbackups/operations/backup.py:335
#, python-format
msgid ""
"Using %s: Must backup all paths at once - Progress notification will be "
"disabled."
msgstr ""

#: fwbackups/operations/backup.py:294 fwbackups/operations/backup.py:337
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s"
msgstr ""

#: fwbackups/operations/backup.py:374
#, python-format
msgid ""
"Path %s is missing or cannot be read and will be excluded from the backup."
msgstr ""
"Der Pfad %s fehlt oder kann nicht gelesen werden und wird von der Sicherung "
"ausgenommen."

#: fwbackups/operations/backup.py:388
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s '%(d)s'"
msgstr ""

#: fwbackups/operations/backup.py:415
msgid "Sending files to server via SFTP"
msgstr "Übertrage Dateien zum Server via SFTP"

#: fwbackups/operations/backup.py:425
msgid "Could not send file(s) or folder to server:"
msgstr "Konnte Datei(en) oder Verzeichnis nicht zum Server übertragen:"

#: fwbackups/operations/backup.py:439
msgid "This function is designed to be subclassed"
msgstr ""

#: fwbackups/operations/backup.py:450
msgid "Starting one-time backup operation"
msgstr "Starte einmaligen Sicherungsvorgang"

#. fmt: Backup-SetName from Backup-Setname-2009-03-22_20-46[.tar[.gz|.bz2]]
#: fwbackups/operations/backup.py:455 fwbackups/operations/backup.py:527
#: fwbackups/operations/backup.py:625 fwbackups/ui/__init__.py:1501
#: fwbackups/ui/__init__.py:1564 fwbackups/ui/__init__.py:1566
msgid "Backup"
msgstr "Sicherung"

#: fwbackups/operations/backup.py:455
msgid "OneTime"
msgstr ""

#: fwbackups/operations/backup.py:469 fwbackups/operations/backup.py:674
msgid "There are no paths to backup!"
msgstr ""

#: fwbackups/operations/backup.py:487 fwbackups/operations/backup.py:689
#, python-format
msgid "`%s' exists and will be overwritten."
msgstr "`%s' existiert bereits und wird überschrieben."

#. might be ntfs
#. All done!
#: fwbackups/operations/backup.py:508
msgid "Finished one-time backup"
msgstr "Einmalige Sicherung abgeschlossen"

#. Execute the command
#: fwbackups/operations/backup.py:595
#, python-format
msgid "Executing '%s' command"
msgstr "Befehl '%s' wird ausgeführt"

#: fwbackups/operations/backup.py:612
msgid "Command returned with a non-zero exit status!"
msgstr ""

#: fwbackups/operations/backup.py:633
#, python-format
msgid "Removing old backup `%(a)s' on %(b)s"
msgstr "Lösche alte Sicherung `%(a)s' auf %(b)s"

#: fwbackups/operations/backup.py:640 fwbackups/operations/backup.py:653
#, python-format
msgid "Removing old backup `%s'"
msgstr "Lösche alte Sicherung `%s'"

#. oldIncrementalBackup = rsync
#: fwbackups/operations/backup.py:646
#, python-format
msgid "Moving  `%s' to `%s'"
msgstr "`%s' wird nach `%s' verschoben"

#. source = is not a rsync backup - remove it and start fresh
#: fwbackups/operations/backup.py:649
#, python-format
msgid "`%s' is not an rsync backup - removing."
msgstr ""

#: fwbackups/operations/backup.py:662
#, python-format
msgid "Starting automatic backup operation of set `%s'"
msgstr "Starte automatisierte Sicherungsvorgang für den Satz `%s'"

#: fwbackups/operations/backup.py:727 fwbackups/ui/__init__.py:2277
#: fwbackups/ui/__init__.py:2435
msgid "There was an error while performing the backup!"
msgstr "Es gab ein Fehler während der Durchführung des Backups!"

#. All done!
#: fwbackups/operations/backup.py:739
#, python-format
msgid "Finished automatic backup operation of set '%s'"
msgstr ""

#: fwbackups/operations/restore.py:47
msgid "Starting restore operation"
msgstr "Starte Wiederherstellungsvorgang"

#. check if server settings are OK
#: fwbackups/operations/restore.py:76
msgid "Attempting to connect to server"
msgstr "Versuche eine Verbindung zum Server aufzubauen"

#: fwbackups/operations/restore.py:89
msgid ""
"The restore source was either not found or it cannot be read due to "
"insufficient permissions."
msgstr ""

#: fwbackups/operations/restore.py:121
msgid "Receiving files from server"
msgstr "Empfange Dateien vom Server"

#: fwbackups/operations/restore.py:132
#, python-format
msgid "Could not receive file from server: %s"
msgstr "Konnte Datei von folgendem Server nicht empfangen: %s"

#. We are dealing with a remote folder - our job here is done
#. Either that or an error was encountered above
#. All done!
#: fwbackups/operations/restore.py:137 fwbackups/operations/restore.py:182
msgid "Finished restore operation"
msgstr "Wiederherstellungsvorgang wurde abgeschlossen"

#. oops, something is up
#: fwbackups/operations/restore.py:149
#, python-format
msgid "Source `%s' is not a file or folder!"
msgstr "Die Quelle `%s' ist keine Datei oder Verzeichnis!"

#. oops, something is up
#: fwbackups/operations/restore.py:158
#, python-format
msgid "Source `%s' is not an archive!"
msgstr "Die Quelle `%s' ist kein Archiv!"

#: fwbackups/operations/restore.py:162
#, python-format
msgid "Source `%s' is not a folder"
msgstr "Die Quelle `%s' ist kein Verzeichnis"

#: fwbackups/operations/restore.py:178
#, python-format
msgid "Traceback: %s"
msgstr ""

#: fwbackups/sftp.py:226
#, python-format
msgid "`%s' is not a file, folder or link! Skipping."
msgstr ""

#: fwbackups/sftp.py:231
msgid "Could not copy some files due to errors:"
msgstr "Konnte einige Dateien aufgrund von Fehlern nicht kopieren:"

#: fwbackups/shutil_modded.py:136
#, python-format
msgid "`%s' isn't a file, folder or link! Skipping."
msgstr "`%s' ist keine Datei, Verzeichnis oder Verknüpfung! Überspringe."

#: fwbackups/shutil_modded.py:147
msgid "Couldn't copy some files due to errors:"
msgstr "Konnte einige Dateien aufgrund von Fehlern nicht kopieren:"

#: fwbackups/ui/__init__.py:226
#, fuzzy, python-format
msgid "<b>Welcome</b>, %s"
msgstr "<b>Willkommen</b>"

#. done in main3Refresh() #self.ui.main3DestinationTypeCombobox.set_active(0)
#. Default Labels...
#: fwbackups/ui/__init__.py:229 fwbackups/ui/__init__.py:1193
#: fwbackups/ui/__init__.py:1298 fwbackups/ui/__init__.py:1680
msgid "Idle"
msgstr "Leerlauf"

#. Default progressbars...
#: fwbackups/ui/__init__.py:234 fwbackups/ui/__init__.py:1192
msgid "Click 'Backup Set Now' to begin"
msgstr "Klicke 'Satz jetzt sichern' um zu beginnen"

#: fwbackups/ui/__init__.py:235
msgid "Click 'Start Backup' to begin"
msgstr ""

#: fwbackups/ui/__init__.py:236
msgid "Click 'Start Restore' to begin"
msgstr ""

#: fwbackups/ui/__init__.py:263
msgid "Could not setup the fwbackups configuration folder"
msgstr "Konnte das fwbackups Konfigurationsverzeichnis nicht einstellen"

#: fwbackups/ui/__init__.py:264 fwbackups/ui/__init__.py:302
#, python-format
msgid "The following error occured: %s"
msgstr "Folgender Fehler ist aufgetreten: %s"

#: fwbackups/ui/__init__.py:271
#, python-format
msgid "Validation error: %s"
msgstr "Validierungsfehler: %s"

#: fwbackups/ui/__init__.py:272
msgid "Preferences could not be read"
msgstr "Einstellungen konnten nicht gelesen werden"

#: fwbackups/ui/__init__.py:272
msgid ""
"The preferences file may be corrupted and could not be read by fwbackups. "
"Would you like to initialize a new one from the default values? If not, "
"fwbackups will exit."
msgstr ""
"Die Einstellungen-Datei ist möglicherweise beschädigt und kann nicht von "
"fwbackups gelesen werden. Möchten Sie eine neue mit den Standardwerten "
"erstellen? Falls nicht wird fwbackups beendet."

#: fwbackups/ui/__init__.py:301
msgid "Could not setup the logger"
msgstr ""

#: fwbackups/ui/__init__.py:325
msgid "Previous installation of fwbackups 1.42.x or older detected"
msgstr "Vorige Installation von fwbackups 1.42.x oder älter gefunden"

#: fwbackups/ui/__init__.py:325
msgid ""
"Because of certain major changes in fwbackups, your configuration must be "
"imported manually. To do this, run fwbackups as the root user and select "
"<i>File > Import</i> from the menu to import your old configuration.\n"
"If this action is not completed, the backups from version 1.42.x <b>will not "
"run automatically</b>.\n"
"<i>Tip: The 1.42.x configuration was stored in /etc/fwbackups</i>."
msgstr ""

#: fwbackups/ui/__init__.py:332
msgid "A backup of /etc/crontab could not be created"
msgstr "Eine Sicherung von /etc/crontab konnte nicht erstellt werden"

#: fwbackups/ui/__init__.py:332
msgid ""
"You may wish to edit /etc/crontab manually and remove any fwbackups-related "
"lines."
msgstr ""
"Sie wünschen eventuell die /etc/crontab manuell zu bearbeiten und bestimmte "
"fwbackups zugehörigen Zeilen entfernen."

#: fwbackups/ui/__init__.py:333
msgid "Could not create a backup of /etc/crontab; refusing to clean up."
msgstr ""

#: fwbackups/ui/__init__.py:336
msgid "Cleaning up /etc/crontab from previous installation of fwbackups"
msgstr "Bereinige /etc/crontab von einer früheren Installation von fwbackups"

#: fwbackups/ui/__init__.py:345
#, python-format
msgid ""
"fwbackups was unable to clean up the system crontab: %s. You may wish to "
"edit /etc/crontab manually and remove any fwbackups-related lines."
msgstr ""

#: fwbackups/ui/__init__.py:346
msgid "Cleanup of the system crontab failed"
msgstr ""

#: fwbackups/ui/__init__.py:351
msgid "fwbackups administrator started"
msgstr ""

#: fwbackups/ui/__init__.py:360
msgid "Would you like to clean up the log file?"
msgstr "Möchten Sie die Logdatei bereinigen?"

#: fwbackups/ui/__init__.py:360
#, python-format
msgid ""
"The log file is becoming large (%s). Would you like to clear it? This will "
"permanently remove all entries from the log."
msgstr ""
"Die Logdatei wird zu groß (%s). Möchten Sie diese bereinigen? Dies wird alle "
"Einträge im Log vollständig löschen."

#: fwbackups/ui/__init__.py:478
msgid "Regenerating crontab"
msgstr ""

#: fwbackups/ui/__init__.py:479
msgid "Please wait... Regenerating crontab"
msgstr ""

#: fwbackups/ui/__init__.py:492
#, python-format
msgid "Could not parse the configuration for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:493
#, python-format
msgid ""
"The set configuration file '%s' failed to validate, so it may not be "
"properly scheduled. Other sets are unaffected by this error."
msgstr ""

#: fwbackups/ui/__init__.py:500
#, python-format
msgid ""
"Internal error: generated entry for set '%s' was not parsable. Please submit "
"a bug report."
msgstr ""

#: fwbackups/ui/__init__.py:503
#, python-format
msgid "Could not schedule automated backups for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:504
msgid ""
"fwbackups could not regenerate a crontab entry because an error occured:\n"
msgstr ""

#: fwbackups/ui/__init__.py:505
#, python-format
msgid ""
"%(a)s\n"
"\n"
"The crontab entry associated with the error was:\n"
"%(b)s"
msgstr ""

#. After all is done, log an message
#: fwbackups/ui/__init__.py:508
#, python-format
msgid "Saving set `%s' to the crontab"
msgstr "Speichere Satz `%s' in die crontab"

#: fwbackups/ui/__init__.py:520
#, python-format
msgid "Unable to write new crontab: %s"
msgstr "Schreiben einer neuen Crontab nicht möglich: %s"

#: fwbackups/ui/__init__.py:521
#, fuzzy
msgid "Error saving backup schedule to crontab"
msgstr "Kann die geplante Sicherung nicht in crontab speichern"

#: fwbackups/ui/__init__.py:521
msgid ""
"Changes made to the backup schedule may not have been correctly saved. If "
"you are using custom cron entry for a backup set, verify the values are "
"valid.\n"
"\n"
msgstr ""

#: fwbackups/ui/__init__.py:525
msgid ""
"A backup of the crontab was restored; the latest changes to the backup "
"schedule not have been saved."
msgstr ""

#: fwbackups/ui/__init__.py:527
#, fuzzy, python-brace-format
msgid "A backup of the crontab could not be restored: {error}"
msgstr "Eine Sicherung des crontab konnte nicht wiederhergestellt werden"

#: fwbackups/ui/__init__.py:533
msgid "fwbackups is working"
msgstr ""

#: fwbackups/ui/__init__.py:534
msgid ""
"An operation is currently in progress. Would you like to cancel it and quit "
"anyways?"
msgstr ""

#: fwbackups/ui/__init__.py:536
msgid "Please wait... Canceling operations"
msgstr "Bitte warten... Breche Vorgang ab"

#: fwbackups/ui/__init__.py:549
msgid "fwbackups detected more than one alive threads!"
msgstr "fwbackups erkannte mehr als einen aktiven Thread!"

#: fwbackups/ui/__init__.py:554
#, python-format
msgid "Closed dead Paramiko thread: %s"
msgstr ""

#. FIXME: Figure out how to kill other thread types. For now, just log.
#: fwbackups/ui/__init__.py:557
#, python-format
msgid "Could not close thread %s!"
msgstr "Konnte den Thread %s nicht schließen!"

#: fwbackups/ui/__init__.py:558
msgid "Please submit a bug report and include this message."
msgstr "Bitte erstelle einen Fehlerbericht und füge diese Meldung hinzu."

#: fwbackups/ui/__init__.py:567 fwbackups/ui/__init__.py:2192
msgid "Could not save backup schedule"
msgstr ""

#: fwbackups/ui/__init__.py:567
msgid ""
"fwbackups was unable to save the backup scheduling information to the "
"crontab. If you are using manual times entry in one of your sets, please "
"verify that all five fields are using the correct syntax."
msgstr ""

#. Shutdown logging & quit the GTK mainloop
#: fwbackups/ui/__init__.py:569
msgid "fwbackups administrator closed"
msgstr ""

#: fwbackups/ui/__init__.py:580
msgid "Creating thread"
msgstr ""

#: fwbackups/ui/__init__.py:581
msgid "testConnection(): Creating thread"
msgstr ""

#: fwbackups/ui/__init__.py:584
msgid "Attempting to connect"
msgstr "Versuche zu verbinden"

#: fwbackups/ui/__init__.py:588
#, python-format
msgid "testConnection(): Thread returning with retval %s"
msgstr ""

#: fwbackups/ui/__init__.py:590
msgid "Success!"
msgstr "Erfolg!"

#: fwbackups/ui/__init__.py:590
#, python-format
msgid "fwbackups was able to connect and authenticate on '%s'."
msgstr "fwbackups konnte sich mit '%s' verbinden und authentifizieren."

#: fwbackups/ui/__init__.py:592
msgid "Remote destination is not usable"
msgstr ""

#: fwbackups/ui/__init__.py:592
#, python-format
msgid ""
"The folder '%(a)s' on '%(b)s' either does not exist or it is not a folder. "
"Please verify your settings and try again."
msgstr ""
"Das Verzeichnis '%(a)s' auf '%(b)s' existiert entweder nicht oder ist kein "
"Verzeichnis. Bitte überprüfen Sie Ihre Einstellungen und versuche es erneut."

#: fwbackups/ui/__init__.py:594 fwbackups/ui/__init__.py:1469
msgid "Authentication failed"
msgstr "Authentifizierung fehlgeschlagen"

#: fwbackups/ui/__init__.py:594
#, python-format
msgid ""
"A connection to '%s' was established, but authentication failed. Please "
"verify the username and password and try again."
msgstr ""
"Eine Verbindung zu '%s' wurde hergestellt, jedoch ist die authentifizierung "
"fehlgeschlagen. Bitte überprüfen Sie den Benutzernamen und Passwort und "
"versuche es erneut."

#: fwbackups/ui/__init__.py:596 fwbackups/ui/__init__.py:600
#, python-format
msgid "A connection to '%s' could not be established"
msgstr "Mit '%s' konnte keine Verbindung aufgebaut werden"

#: fwbackups/ui/__init__.py:596
#, python-format
msgid "Error %(a)s: %(b)s"
msgstr "Fehler %(a)s: %(b)s"

#: fwbackups/ui/__init__.py:598
#, python-format
msgid "The server '%s' is not responding"
msgstr "Der Server '%s' antwortet nicht"

#: fwbackups/ui/__init__.py:598 fwbackups/ui/__init__.py:1476
msgid "Please verify your settings and try again."
msgstr "Bitte überprüfen Sie Ihre Einstellungen und versuche es erneut."

#: fwbackups/ui/__init__.py:600
#, python-format
msgid "Error: %s. Please verify your settings and try again."
msgstr ""
"Fehler: %s. Bitte überprüfen Sie Ihre Einstellungen und versuche es erneut."

#: fwbackups/ui/__init__.py:602 fwbackups/ui/__init__.py:1168
#: fwbackups/ui/__init__.py:1481
msgid "Unexpected error"
msgstr "Unerwarteter Fehler"

#: fwbackups/ui/__init__.py:602
#, fuzzy
msgid "An unknown error occurred while testing for connectivity."
msgstr "Ein Fehler trat beim Importieren von gtk/gobject auf."

#: fwbackups/ui/__init__.py:615 fwbackups/ui/__init__.py:618
#: fwbackups/ui/__init__.py:903 fwbackups/widgets.py:619
#: fwbackups/widgets.py:622
msgid "Choose file(s)"
msgstr "Datei(en) auswählen"

#: fwbackups/ui/__init__.py:617 fwbackups/ui/__init__.py:699
#: fwbackups/ui/__init__.py:905 fwbackups/ui/__init__.py:975
#: fwbackups/ui/__init__.py:1334 fwbackups/ui/__init__.py:1694
#: fwbackups/ui/__init__.py:1708 fwbackups/ui/__init__.py:1722
#: fwbackups/widgets.py:621 fwbackups/widgets.py:633
msgid "_Open"
msgstr ""

#: fwbackups/ui/__init__.py:617 fwbackups/ui/__init__.py:699
#: fwbackups/ui/__init__.py:905 fwbackups/ui/__init__.py:975
#: fwbackups/ui/__init__.py:1334 fwbackups/ui/__init__.py:1694
#: fwbackups/ui/__init__.py:1708 fwbackups/ui/__init__.py:1722
#: fwbackups/widgets.py:621 fwbackups/widgets.py:633 fwbackups/widgets.py:740
#, fuzzy
msgid "_Cancel"
msgstr "Wird abgebrochen..."

#: fwbackups/ui/__init__.py:619
msgid "Configuration files (*.conf)"
msgstr "Konfigurationsdateien (*.conf)"

#: fwbackups/ui/__init__.py:680
msgid "File Exists"
msgstr "Datei vorhanden"

#: fwbackups/ui/__init__.py:681
#, python-format
msgid "'%s.conf' already exists! Would you like to overwrite it?"
msgstr "'%s.conf' ist bereits vorhanden! Möchten Sie sie überschreiben?"

#: fwbackups/ui/__init__.py:687
#, python-format
msgid "Exported set `%(a)s' to `%(b)s'"
msgstr "Exportiere den Satz `%(a)s' nach `%(b)s'"

#: fwbackups/ui/__init__.py:697 fwbackups/ui/__init__.py:700
#: fwbackups/ui/__init__.py:906 fwbackups/ui/__init__.py:973
#: fwbackups/ui/__init__.py:976 fwbackups/ui/__init__.py:1332
#: fwbackups/ui/__init__.py:1335 fwbackups/widgets.py:631
#: fwbackups/widgets.py:634
msgid "Choose folder(s)"
msgstr "Ordner auswählen"

#: fwbackups/ui/__init__.py:707
msgid "Sets exported"
msgstr "Sätze exportiert"

#: fwbackups/ui/__init__.py:707
msgid "The selected sets were exported successfully."
msgstr "Die ausgewählten Sätze wurden erfolgreich exportiert."

#: fwbackups/ui/__init__.py:734 fwbackups/ui/__init__.py:1119
#: fwbackups/ui/__init__.py:1136 fwbackups/ui/__init__.py:1210
#: fwbackups/ui/__init__.py:2247
msgid "No set has been selected"
msgstr "Es wurde kein Satz ausgewählt"

#: fwbackups/ui/__init__.py:734
msgid "You must select a set to duplicate."
msgstr "Sie müssen einen Satz zum duplizieren auswählen."

#: fwbackups/ui/__init__.py:738
msgid "_copy"
msgstr ""

#: fwbackups/ui/__init__.py:892
#, python-format
msgid "Resetting preference '%(a)s' to 0"
msgstr ""

#: fwbackups/ui/__init__.py:993 fwbackups/ui/__init__.py:1256
#: fwbackups/ui/__init__.py:1261 fwbackups/ui/__init__.py:1352
#: fwbackups/ui/__init__.py:1535 fwbackups/ui/__init__.py:1610
#: fwbackups/ui/__init__.py:1647 fwbackups/ui/__init__.py:2152
#: fwbackups/ui/__init__.py:2157
msgid "Missing information"
msgstr "Fehlende Information"

#: fwbackups/ui/__init__.py:993
msgid "Please complete the host, username, folder and port fields."
msgstr ""
"Bitte vervollständige das Host, Benutzername, Verzeichnis und Port-Feld."

#: fwbackups/ui/__init__.py:1119
msgid "You must select a set to edit."
msgstr "Sie müssen einen Satz zum bearbeiten auswählen."

#: fwbackups/ui/__init__.py:1136
msgid "You must select a set to remove."
msgstr "Sie müssen einen Satz zum entfernen auswählen."

#: fwbackups/ui/__init__.py:1138
#, python-format
msgid "Delete backup set '%s'?"
msgstr "Sicherungssatz '%s' löschen?"

#: fwbackups/ui/__init__.py:1138
msgid ""
"This action will permanently delete the backup set configuration. This "
"action will not delete any existing backups, or files and folders associated "
"with the set."
msgstr ""

#: fwbackups/ui/__init__.py:1145 fwbackups/ui/__init__.py:1153
#, python-format
msgid ""
"An error occured while removing set `%(a)s':\n"
"%(b)s"
msgstr ""
"Ein Fehler trat beim entfernen des Satzes `%(a)s' auf:\n"
"%(b)s"

#: fwbackups/ui/__init__.py:1146
#, python-format
msgid "Could not remove backup set '%s'"
msgstr "Kann das Sicherungsset '%s' nicht löschen"

#: fwbackups/ui/__init__.py:1154
#, python-format
msgid "Could not remove the automated backup schedule for set '%s'"
msgstr ""
"Kann die geplante automatisierte Sicherung für das Set '%s' nicht löschen"

#: fwbackups/ui/__init__.py:1158
#, python-format
msgid "Removing set `%s'"
msgstr "Satz `%s' wird entfernt"

#: fwbackups/ui/__init__.py:1168
#, python-format
msgid ""
"An unexpected error occured while attempting to obtain the selected set:\n"
"%s"
msgstr ""

#: fwbackups/ui/__init__.py:1210
msgid "You must select a set to restore."
msgstr "Sie müssen einen Satz zum wiederherstellen auswählen."

#: fwbackups/ui/__init__.py:1256 fwbackups/ui/__init__.py:2152
msgid "Please fill in the Folder field."
msgstr "Bitte füllen Sie das Verzeichnisfeld aus."

#: fwbackups/ui/__init__.py:1261 fwbackups/ui/__init__.py:2157
msgid "Please fill in the Host, Username, Port and Folder fields."
msgstr "Bitte füllen Sie das Host, Benutzername, Port und Verzeichnisfeld aus."

#: fwbackups/ui/__init__.py:1352 fwbackups/ui/__init__.py:1535
#: fwbackups/ui/__init__.py:1647
msgid "Please complete all of the host, username, folder and port fields."
msgstr ""
"Bitte vervollständige alle Host, Benutzername, Verzeichnis und Port-Felder."

#: fwbackups/ui/__init__.py:1376
msgid "Log cleared"
msgstr "Protokoll bereinigt"

#: fwbackups/ui/__init__.py:1381
msgid "Clear the old log entries?"
msgstr "Die alten Protokolleinträge bereinigen?"

#: fwbackups/ui/__init__.py:1382
msgid "This action will permanently remove all log entries."
msgstr "Diese Aktion wird alle Log Einträge permanent löschen."

#: fwbackups/ui/__init__.py:1400
#, python-format
msgid "Log saved to file `%s'"
msgstr "Protokoll in Datei `%s' gespeichert"

#: fwbackups/ui/__init__.py:1466
msgid "Previous backups could not be found"
msgstr ""

#: fwbackups/ui/__init__.py:1467
#, python-format
msgid "The destination folder for set '%s' was not found."
msgstr "Das Zielverzeichnis für Satz '%s' wurde nicht gefunden."

#: fwbackups/ui/__init__.py:1470
#, python-format
msgid ""
"fwbackups was unable to authenticate on the remote server. Please verify the "
"username and password for set '%s' and try again."
msgstr ""
"fwbackups konnte sich nicht auf dem entfernten Server authentifizieren. "
"Bitte überprüfe den Benutzernamen und das Passwort für den Satz '%s' und "
"versuche es erneut."

#: fwbackups/ui/__init__.py:1472 fwbackups/ui/__init__.py:1478
msgid "Connection failed"
msgstr "Verbindung fehlgeschlagen"

#: fwbackups/ui/__init__.py:1473
#, python-format
msgid ""
"A connection to the server could not be established:\n"
"Error %(a)s: %(b)s\n"
"Please verify your settings and try again."
msgstr ""

#: fwbackups/ui/__init__.py:1475
msgid "Remote server is not responding"
msgstr ""

#: fwbackups/ui/__init__.py:1479
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s\n"
"Please verify your settings and try again."
msgstr ""

#: fwbackups/ui/__init__.py:1493
#, python-format
msgid ""
"Error obtaining file listing in destination %(a)s:\n"
"%(b)s"
msgstr ""

#: fwbackups/ui/__init__.py:1494
#, python-format
msgid "Could not get a list of old backups for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:1494
msgid ""
"If the destination is on removable media such as an external hard disk, "
"please attach it and try again."
msgstr ""
"Falls das Zeil auf einem Wechselmedium, wie beispielsweise eine externe "
"Festplatte ist, schließe diese bitte an und versuche es erneut."

#. We can't start a restore if there are no set dates
#: fwbackups/ui/__init__.py:1504 fwbackups/ui/__init__.py:1618
#: fwbackups/ui/__init__.py:1619
msgid "No backups found"
msgstr "Keine Sicherungen gefunden"

#: fwbackups/ui/__init__.py:1610
msgid "Please select a backup date."
msgstr "Bitte wähle ein Datum für die Sicherung."

#: fwbackups/ui/__init__.py:1619
#, python-format
msgid ""
"The backup set '%s' does not have any stored backups yet! Choose another "
"set, or alternatively choose a different restore source."
msgstr ""

#: fwbackups/ui/__init__.py:1626 fwbackups/ui/__init__.py:1637
msgid "Restore source"
msgstr ""

#: fwbackups/ui/__init__.py:1626
msgid "Please enter the location of the local archive."
msgstr ""

#: fwbackups/ui/__init__.py:1629
msgid "Wrong file type"
msgstr "Falscher Dateityp"

#: fwbackups/ui/__init__.py:1630
msgid ""
"The file you selected is not a supported archive.\n"
"Supported archives types are tar with no, gzip or bzip2 compression."
msgstr ""

#: fwbackups/ui/__init__.py:1637
msgid "Please enter the location of the local folder."
msgstr ""

#: fwbackups/ui/__init__.py:1692 fwbackups/ui/__init__.py:1695
#: fwbackups/ui/__init__.py:1706 fwbackups/ui/__init__.py:1709
#: fwbackups/ui/__init__.py:1720 fwbackups/ui/__init__.py:1723
msgid "Select a Folder"
msgstr "Wählen Sie einen Ordner aus"

#: fwbackups/ui/__init__.py:1737 fwbackups/ui/__init__.py:1740
msgid "Invalid set name"
msgstr "Ungültiger Satzname"

#: fwbackups/ui/__init__.py:1737
msgid "Please enter a set name."
msgstr "Bitte geben Sie einen Satznamen ein."

#: fwbackups/ui/__init__.py:1740
msgid ""
"'temporary_name' is a reserved name. Please choose another name for the set."
msgstr ""

#: fwbackups/ui/__init__.py:1744
#, python-format
msgid "Overwrite settings for set '%s'?"
msgstr "Die Einstellungen für das Set '%s' überschreiben?"

#: fwbackups/ui/__init__.py:1745
msgid ""
"This will overwrite the stored settings with the current ones. Are you sure "
"you want to continue?"
msgstr ""
"Dies wird die gespeicherten Einstellungen mit den aktuellen Einstellungen "
"überschreiben. Möchten Sie den Vorgang fortsetzen?"

#: fwbackups/ui/__init__.py:1856
msgid "Error parsing configuration file"
msgstr ""

#: fwbackups/ui/__init__.py:1857
msgid "fwbackups will using the default times instead."
msgstr "fwbackups wird die Standardzeiten stattdessen verwenden."

#: fwbackups/ui/__init__.py:1870
#, python-format
msgid "Unknown destination type `%s'"
msgstr "Unbekannter Zieltyp `%s'"

#: fwbackups/ui/__init__.py:2072
msgid "Error creating the automated backup schedules"
msgstr ""

#: fwbackups/ui/__init__.py:2073
#, python-format
msgid ""
"The crontab could not be written because an error occured:\n"
"%s"
msgstr ""

#: fwbackups/ui/__init__.py:2108 fwbackups/widgets.py:712
msgid "Parsing configuration files"
msgstr ""

#: fwbackups/ui/__init__.py:2123 fwbackups/widgets.py:718
#, python-format
msgid "Refusing to parse file `%s': configuration files must end in `.conf'"
msgstr ""

#: fwbackups/ui/__init__.py:2175
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s"
msgstr "Umbenennen von Satz `%(a)s' zu `%(b)s"

#: fwbackups/ui/__init__.py:2177
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s failed: %(c)s"
msgstr "Umbenennen von Satz `%(a)s' zu `%(b)s fehlgeschlagen: %(c)s"

#: fwbackups/ui/__init__.py:2178
#, python-format
msgid "Could not rename set '%(a)s' to '%(b)s'"
msgstr "Konnte Satz `%(a)s' nicht zu `%(b)s' umbenennen"

#. creating a set
#: fwbackups/ui/__init__.py:2184
#, python-format
msgid "Creating set `%s'"
msgstr "Erstelle Satz `%s'"

#. editing a set
#: fwbackups/ui/__init__.py:2188
#, python-format
msgid "Saving changes to set `%s'"
msgstr "Speichere Änderungen an Satz `%s'"

#: fwbackups/ui/__init__.py:2192
msgid ""
"Your set configuration changes were saved, but fwbackups was unable to save "
"the backup scheduling information to the crontab. If you are using manual "
"times entry, please verify that all five fields are using the correct syntax."
msgstr ""

#: fwbackups/ui/__init__.py:2230 fwbackups/ui/__init__.py:2391
#, python-format
msgid "[%(a)i/%(b)i] Backing up: %(c)s"
msgstr "[%(a)i/%(b)i] Sichere: %(c)s"

#: fwbackups/ui/__init__.py:2233 fwbackups/ui/__init__.py:2394
#, python-format
msgid "[%(a)i/%(b)i] Backing up files... Please wait"
msgstr "[%(a)i/%(b)i] Sichere Dateien... Bitte warten"

#: fwbackups/ui/__init__.py:2235 fwbackups/ui/__init__.py:2396
msgid "Cleaning old backups"
msgstr "Bereinige alte Sicherungen"

#: fwbackups/ui/__init__.py:2237 fwbackups/ui/__init__.py:2398
msgid "Sending files to remote server"
msgstr "Sende Dateien zum entfernten Server"

#: fwbackups/ui/__init__.py:2239 fwbackups/ui/__init__.py:2400
msgid "Executing user command"
msgstr "Benutzerbefehl wird ausgeführt"

#: fwbackups/ui/__init__.py:2247
msgid "You must select to initiate a manual set backup."
msgstr ""

#: fwbackups/ui/__init__.py:2253 fwbackups/ui/__init__.py:2409
#: fwbackups/ui/__init__.py:2499
msgid "Initializing"
msgstr "Initialisierungsvorgang"

#: fwbackups/ui/__init__.py:2255 fwbackups/ui/__init__.py:2411
#, fuzzy
msgid "Backup started"
msgstr "Sicherung fehlgeschlagen!"

#: fwbackups/ui/__init__.py:2255
#, python-format
msgid "Starting a set backup operation of '%(a)s'"
msgstr ""

#: fwbackups/ui/__init__.py:2258 fwbackups/ui/__init__.py:2316
#: fwbackups/ui/__init__.py:2418 fwbackups/ui/__init__.py:2478
#: fwbackups/ui/__init__.py:2504 fwbackups/ui/__init__.py:2562
msgid "Please wait..."
msgstr "Bitte warten..."

#: fwbackups/ui/__init__.py:2264 fwbackups/ui/__init__.py:2422
#: fwbackups/ui/__init__.py:2509
msgid "Working"
msgstr ""

#. thread returned
#: fwbackups/ui/__init__.py:2272 fwbackups/ui/__init__.py:2430
#: fwbackups/ui/__init__.py:2517
#, python-format
msgid "Thread returned with retval %s"
msgstr ""

#. error
#: fwbackups/ui/__init__.py:2281 fwbackups/ui/__init__.py:2299
#: fwbackups/ui/__init__.py:2439 fwbackups/ui/__init__.py:2458
#: fwbackups/ui/__init__.py:2523 fwbackups/ui/__init__.py:2543
msgid "<span color=\"Red\">Error</span>"
msgstr "<span color=\"Red\">Fehler</span>"

#: fwbackups/ui/__init__.py:2282 fwbackups/ui/__init__.py:2443
#, python-format
msgid "An error occurred while initializing the backup operation: %s"
msgstr ""

#: fwbackups/ui/__init__.py:2286 fwbackups/ui/__init__.py:2444
msgid "Error initializing backup"
msgstr "Fehler beim Initialisieren der Sicherung"

#: fwbackups/ui/__init__.py:2296 fwbackups/ui/__init__.py:2455
#, fuzzy
msgid "Backup complete"
msgstr "Sicherungssätze"

#: fwbackups/ui/__init__.py:2296
#, python-format
msgid "Finished the automatic backup operation of set `%(a)s'"
msgstr ""

#: fwbackups/ui/__init__.py:2297 fwbackups/ui/__init__.py:2456
#: fwbackups/ui/__init__.py:2540
msgid "<span color=\"dark green\">Operation complete</span>"
msgstr "<span color=\"dark green\">Vorgang abgeschlossen</span>"

#: fwbackups/ui/__init__.py:2301 fwbackups/ui/__init__.py:2460
#, fuzzy
msgid "Error during backup"
msgstr "Fehler beim Initialisieren der Sicherung"

#: fwbackups/ui/__init__.py:2301
#, python-format
msgid ""
"An error occured while performing the automatic backup operation of set "
"`%(a)s'"
msgstr ""

#: fwbackups/ui/__init__.py:2304 fwbackups/ui/__init__.py:2465
#, fuzzy
msgid "Backup cancelled"
msgstr "Sicherung fehlgeschlagen!"

#: fwbackups/ui/__init__.py:2304
#, python-format
msgid "The automatic backup operation of set `%(a)s' was cancelled"
msgstr ""
"Der automatische Sicherungsvorgang für den Satz `%(a)s' wurde abgebrochen"

#: fwbackups/ui/__init__.py:2305 fwbackups/ui/__init__.py:2466
#: fwbackups/ui/__init__.py:2551
msgid "<span color=\"red\">Operation cancelled</span>"
msgstr "<span color=\"red\">Vorgang abgebrochen</span>"

#: fwbackups/ui/__init__.py:2306 fwbackups/ui/__init__.py:2467
#: fwbackups/ui/__init__.py:2552
msgid "Operation cancelled"
msgstr "Vorgang abgebrochen"

#: fwbackups/ui/__init__.py:2317 fwbackups/ui/__init__.py:2479
#: fwbackups/ui/__init__.py:2563
msgid "Cancelling..."
msgstr "Wird abgebrochen..."

#: fwbackups/ui/__init__.py:2411
msgid "Starting a one-time backup operation"
msgstr "Starte einen einmaligen Sicherungsvorgang"

#: fwbackups/ui/__init__.py:2455
msgid "Finished the one-time backup operation"
msgstr "Der einmalige Sicherungsvorgang wurde abgeschlossen"

#: fwbackups/ui/__init__.py:2460
msgid "An error occured while performing the one-time backup operation"
msgstr ""
"Ein Fehler trat während dem ausführen des einmaligen Sicherungsvorgangs auf."

#: fwbackups/ui/__init__.py:2465
msgid "The one-time backup operation was cancelled"
msgstr "Der einmalige Sicherungsvorgang wurde abgebrochen"

#. no "current file" yet
#: fwbackups/ui/__init__.py:2491
msgid "Receiving files from remote server"
msgstr "Empfange Dateien vom Remote-Server"

#. we have a 'current file'
#: fwbackups/ui/__init__.py:2493
#, python-format
msgid "Restoring: %s"
msgstr "Wiederherstellung: %s"

#: fwbackups/ui/__init__.py:2501
#, fuzzy
msgid "Restore started"
msgstr "Wiederherstellung fehlgeschlagen!"

#: fwbackups/ui/__init__.py:2501
msgid "Starting a restore operation"
msgstr "Starte einen Wiederherstellungsvorgang"

#: fwbackups/ui/__init__.py:2519
msgid ""
"There was an error while performing the restore! Enable debug messages for "
"more information."
msgstr ""

#: fwbackups/ui/__init__.py:2526
#, python-format
msgid "An error occurred while initializing the restore operation: %s"
msgstr ""

#: fwbackups/ui/__init__.py:2527
msgid "Error initializing restore operation"
msgstr ""

#: fwbackups/ui/__init__.py:2539
#, fuzzy
msgid "Restore finished"
msgstr "Wiederherstellung fehlgeschlagen!"

#: fwbackups/ui/__init__.py:2539
msgid "Finished the restore operation"
msgstr "Der Wiederherstellungsvorgang wurde abgeschlossen"

#: fwbackups/ui/__init__.py:2545
msgid "Error during restore"
msgstr ""

#: fwbackups/ui/__init__.py:2545
msgid "An error occured while performing the restore operation"
msgstr ""

#: fwbackups/ui/__init__.py:2550
#, fuzzy
msgid "Restore cancelled"
msgstr "Wiederherstellung fehlgeschlagen!"

#: fwbackups/ui/__init__.py:2550
msgid "The restore operation was cancelled"
msgstr "Der Wiederherstellungsvorgang wurde abgebrochen"

#: fwbackups/widgets.py:149 fwbackups/widgets.py:192
msgid "CRITICAL"
msgstr "KRITISCH"

#: fwbackups/widgets.py:149 fwbackups/widgets.py:192
msgid "ERROR"
msgstr "FEHLER"

#: fwbackups/widgets.py:151 fwbackups/widgets.py:194
msgid "WARNING"
msgstr "WARNUNG"

#: fwbackups/widgets.py:164 fwbackups/widgets.py:188
msgid "Previous log messages"
msgstr "Vorherige Protokollmeldungen"

#: fwbackups/widgets.py:168 fwbackups/widgets.py:201
msgid "No previous log messages to display"
msgstr ""

#: fwbackups/widgets.py:169 fwbackups/widgets.py:180
msgid "Current session's log messages"
msgstr ""

#: fwbackups/widgets.py:536
msgid "Access"
msgstr "Zugriff"

#: fwbackups/widgets.py:542
msgid "Path"
msgstr "Pfad"

#: fwbackups/widgets.py:658
msgid "Please select a path before choosing an action."
msgstr "Bitte wähle einen Pfad, bevor Sie eine Aktion auswählen."

#: fwbackups/widgets.py:691
msgid "Export"
msgstr "Exportieren"

#: fwbackups/widgets.py:697
msgid "Set"
msgstr "Satz"

#: fwbackups/widgets.py:732
msgid "Bug Report"
msgstr "Fehlerbericht"

#: fwbackups/widgets.py:740
msgid "_Save"
msgstr ""

#~ msgid "*** Initializing files"
#~ msgstr "*** Dateien werden initialisiert"

#, python-format
#~ msgid ""
#~ "Folder %s exists and will be emptied. Press <Enter> to confirm or "
#~ "<ctrl+c> to cancel..."
#~ msgstr ""
#~ "Verzeichnis %s existiert und wird geleert. Drücke <Enter> zum bestätigen "
#~ "oder <ctrl+c> um abzubrechen..."

#, python-format
#~ msgid "Cleaning folder %s..."
#~ msgstr "Verzeichnis %s wird bereinigt..."

#~ msgid "Hostname [localhost]: "
#~ msgstr "Hostname [localhost]: "

#~ msgid "Port [22]: "
#~ msgstr "Port [22]: "

#~ msgid "The port field can only contain numbers. Please try again."
#~ msgstr "Das Port-Feld darf nur Nummern enthalten. Bitte erneut versuchen."

#, python-format
#~ msgid "Username [%s]: "
#~ msgstr "Benutzername [%s]: "

#~ msgid "Password: "
#~ msgstr "Passwort: "

#, python-format
#~ msgid "Remote folder [%s]: "
#~ msgstr "Entfernter Ordner [%s]: "

#, python-format
#~ msgid "Error: %s"
#~ msgstr "Fehler: %s"

#~ msgid "Run with --help for usage information."
#~ msgstr "Starte mit --help für Information über die Verwendung."

#, python-format
#~ msgid "The set configuration for '%s' was not found - skipping."
#~ msgstr "Die Satzkonfiguration für '%s' wurde nicht gefunden - überspringe."

#~ msgid "An error occurred while initializing the backup operation!"
#~ msgstr "Ein Fehler trat beim initialisieren des Sicherungsvorgangs auf!"

#~ msgid "You must be root to set a niceness below 0"
#~ msgstr "Sie müssen root sein um einen niceness Wert unter 0 einzustellen"

#~ msgid "Nice value must be an integer between -20 and 19"
#~ msgstr "Nice Wert muss eine Ganzzahl zwischen -20 und 19 sein"

#~ msgid "Requires at least one path to backup and a destination"
#~ msgstr "Benötigt mindestens einen Pfad zum Sichern und ein Ziel"

#~ msgid "Destination type was not specified"
#~ msgstr "Zieltyp wurde nicht festgelegt"

#~ msgid "Please make sure you have a valid GTK+ Runtime Environment."
#~ msgstr ""
#~ "Bitte vergewissern Sie sich, dass Sie eine funktionierende GTK+ "
#~ "Laufzeitumgebung haben."

#, python-format
#~ msgid "fwbackups bug report written saved at %s"
#~ msgstr "fwbackups Fehlerbericht wurde gespeichert unter %s"

#~ msgid "Could not write bug report due to insufficient permissions."
#~ msgstr ""
#~ "Konnte den Fehlerbericht aufgrund fehlender Berechtigungen nicht "
#~ "schreiben."

#~ msgid "Please install pycrypto (python-crypto)"
#~ msgstr "Bitte installiere pycrypto (python-crypto) "

#~ msgid "Please install paramiko (python-paramiko)"
#~ msgstr "Bitte installiere paramiko (python-paramiko)"

#~ msgid "Checking permissions"
#~ msgstr "Überprüfe Berechtigungen"

#~ msgid "Ready!"
#~ msgstr "Bereit!"

#~ msgid "Select file(s)"
#~ msgstr "Datei(en) auswählen"

#~ msgid "Please enter a Pycron installation directory."
#~ msgstr "Bitte gebe ein Pycron Installationsverzeichnis ein."

#~ msgid "Configuration not found"
#~ msgstr "Konfiguration nicht gefunden"

#~ msgid "Automated restore not supported"
#~ msgstr "Automatisierte Wiederherstellung wird nicht unterstützt"

#~ msgid "Status"
#~ msgstr "Status"

#~ msgid "Show this program's version and exit"
#~ msgstr "Programmversion anzeigen und beenden"

#~ msgid "start GUI minimized in the system tray"
#~ msgstr "starte GUI minimiert beim Systemstart"

#~ msgid "<span size=\"large\" weight=\"bold\">Overview</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Übersicht</span>"

#~ msgid "_New Set"
#~ msgstr "_Neuer Satz"

#~ msgid "Ed_it Set"
#~ msgstr "Bearbe_ite Sätze"

#~ msgid "_Backup Set Now"
#~ msgstr "Satz jetzt sichern"

#~ msgid "Re_store Set"
#~ msgstr "_Satz wiederherstellen"

#~ msgid "<span size=\"large\" weight=\"bold\">Backups Sets</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Sicherungssätze</span>"

#~ msgid "_Add File(s)"
#~ msgstr "D_atei(en) hinzufügen"

#~ msgid "_Add Folder(s)"
#~ msgstr "_Ordner hinzufügen"

#~ msgid ""
#~ "Local folder\n"
#~ "Remote folder (SSH)"
#~ msgstr ""
#~ "Lokales Verzeichnis\n"
#~ "Entferntes Verzeichnis (SSH)"

#~ msgid "_Browse..."
#~ msgstr "_Durchsuchen..."

#~ msgid ""
#~ "gzip: fast, lightweight\n"
#~ "bzip2: slower, more efficient"
#~ msgstr ""
#~ "gzip: schnell, ressourcenschonend\n"
#~ "bzip2: langsamer, effizienter"

#~ msgid "_Back"
#~ msgstr "_Zurück"

#~ msgid "_Next"
#~ msgstr "Weiter"

#~ msgid "_Start Backup"
#~ msgstr "_Sicherung starten"

#~ msgid "<span size=\"large\" weight=\"bold\">One-Time Backup</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Einmalige Sicherung</span>"

#~ msgid "<span size=\"large\" weight=\"bold\">Log Viewer</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Log Betrachter</span>"

#~ msgid "_File"
#~ msgstr "_Datei"

#~ msgid "Create a new backup set"
#~ msgstr "Erstelle einen neuen Sicherungssatz"

#~ msgid "Import a set from a .conf file"
#~ msgstr "Importiere einen Satz aus einer .conf Datei"

#~ msgid "_Import Sets"
#~ msgstr "_Importiere Sätze"

#~ msgid "Export one or more sets to .conf files"
#~ msgstr "Exportiere eine oder mehrere Sätze in eine .conf Datei"

#~ msgid "E_xport Sets"
#~ msgstr "E_xportiere Sätze"

#~ msgid "_Edit"
#~ msgstr "B_earbeiten"

#~ msgid "Edit the selected backup set"
#~ msgstr "Bearbeite den ausgewählten Sicherungssatz"

#~ msgid "_Edit Set"
#~ msgstr "Satz b_earbeiten"

#~ msgid "Remove the selected backup set"
#~ msgstr "Entferne den ausgewählten Sicherungssatz"

#~ msgid "Duplicate the selected backup set"
#~ msgstr "Dupliziere den ausgewählten Sicherungssatz"

#~ msgid "D_uplicate Set"
#~ msgstr "D_upliziere Satz"

#~ msgid "_View"
#~ msgstr "_Ansicht"

#~ msgid "Switch to Overview"
#~ msgstr "Wechsel zur Übersicht"

#~ msgid "_Overview"
#~ msgstr "_Übersicht"

#~ msgid "Switch to One-Time Backup"
#~ msgstr "Wechsel zur einmaligen Sicherung"

#~ msgid "O_ne-Time Backup"
#~ msgstr "Ei_nmalige Sicherung"

#~ msgid "Switch to Log Viewer"
#~ msgstr "Wechsel zum Log-Betrachter"

#~ msgid "_Log"
#~ msgstr "Protoko_ll"

#~ msgid "_Restore"
#~ msgstr "Wiede_rherstellen"

#~ msgid "_Help"
#~ msgstr "_Hilfe"

#~ msgid "Check for _Updates"
#~ msgstr "Auf Aktualisierungen prüfen"

#~ msgid "About fwbackups"
#~ msgstr "Über fwbackups"

#~ msgid ""
#~ "<span color=\"blue\"><u>http://www.diffingo.com/opensource</u></span>"
#~ msgstr ""
#~ "<span color=\"blue\"><u>http://www.diffingo.com/opensource</u></span>"

#~ msgid "<span size=\"small\">(C) 2005 - 2010 Stewart Adam</span>"
#~ msgstr "<span size=\"small\">(C) 2005 - 2010 Stewart Adam</span>"

#, no-c-format
#~ msgid "<span size=\"xx-large\" weight=\"bold\">fwbackups %s</span>"
#~ msgstr "<span size=\"xx-large\" weight=\"bold\">fwbackups %s</span>"

#~ msgid "License"
#~ msgstr "Lizenz"

#~ msgid "Credits"
#~ msgstr "Credits"

#~ msgid "Select a file or folder"
#~ msgstr "Wählen Sie eine Datei oder einen Ordner aus"

#~ msgid "Save to..."
#~ msgstr "Speichern nach..."

#~ msgid "Status: fwbackups is running"
#~ msgstr "Status: fwbackups läuft"

#~ msgid "_Show Administrator"
#~ msgstr "Admini_strator anzeigen"

#~ msgid "Edit preferences"
#~ msgstr "Einstellungen bearbeiten"

#~ msgid "_Preferences"
#~ msgstr "_Einstellungen"

#~ msgid "_Quit"
#~ msgstr "_Beenden"

#~ msgid "Export to:"
#~ msgstr "Exportieren nach:"

#~ msgid "Browse..."
#~ msgstr "Durchsuchen..."

#~ msgid "Start _Restore"
#~ msgstr "Wiede_rherstellung starten"

#~ msgid "Show tray icon"
#~ msgstr "Zeige Taskleistensymbol"

#~ msgid "Start minimized"
#~ msgstr "Minimiert starten"

#~ msgid "Always show debug messages in the log"
#~ msgstr "Zeige immer Debug-Meldungen im Log"

#~ msgid "Start fwbackups (minimized) when I login"
#~ msgstr "Starte fwbackups (minimiert) wenn Sie sich anmelden"

#~ msgid "Pycron installation directory:"
#~ msgstr "Pycron-Installationsverzeichnis:"

#~ msgid "<b>Windows-specific options</b>"
#~ msgstr "<b>Windows-spezifische Optionen</b>"

#~ msgid "<b>Day(s) of the Week</b>"
#~ msgstr "<b>Tag(e) in der Woche</b>"

#~ msgid "<b>Month(s)</b>"
#~ msgstr "<b>Monat(e)</b>"

#~ msgid " "
#~ msgstr " "

#~ msgid "<b>Day(s) of Month</b>"
#~ msgstr "<b>Tag(e) im Monat</b>"

#~ msgid "<b>Hour(s)</b>"
#~ msgstr "<b>Stunde(n)</b>"

#~ msgid "<b>Minute(s)</b>"
#~ msgstr "<b>Minute(n)</b>"

#~ msgid ""
#~ "January\n"
#~ "February\n"
#~ "March\n"
#~ "April\n"
#~ "May\n"
#~ "June\n"
#~ "July\n"
#~ "August\n"
#~ "September\n"
#~ "October\n"
#~ "November\n"
#~ "December"
#~ msgstr ""
#~ "Januar\n"
#~ "Februar\n"
#~ "März\n"
#~ "April\n"
#~ "Mai\n"
#~ "Juni\n"
#~ "Juli\n"
#~ "August\n"
#~ "September\n"
#~ "Oktober\n"
#~ "November\n"
#~ "Dezember"

#~ msgid ""
#~ "Sunday\n"
#~ "Monday\n"
#~ "Tuesday\n"
#~ "Wednesday\n"
#~ "Thurday\n"
#~ "Friday\n"
#~ "Saturday"
#~ msgstr ""
#~ "Sonntag\n"
#~ "Montag\n"
#~ "Dienstag\n"
#~ "Mittwoch\n"
#~ "Donnerstag\n"
#~ "Freitag\n"
#~ "Samstag"

#~ msgid ""
#~ "Sundays\n"
#~ "Mondays\n"
#~ "Tuesdays\n"
#~ "Wednesdays\n"
#~ "Thurdays\n"
#~ "Fridays\n"
#~ "Saturdays"
#~ msgstr ""
#~ "Sonntage\n"
#~ "Montage\n"
#~ "Dienstage\n"
#~ "Mittwoche\n"
#~ "Donnerstage\n"
#~ "Freitage\n"
#~ "Samstage"

#~ msgid ""
#~ "0 (12am)\n"
#~ "1 (1am)\n"
#~ "2 (2am)\n"
#~ "3 (3am)\n"
#~ "4 (4am)\n"
#~ "5 (5am)\n"
#~ "6 (6am)\n"
#~ "7 (7am)\n"
#~ "8 (8am)\n"
#~ "9 (9am)\n"
#~ "10 (10am)\n"
#~ "11 (11am)\n"
#~ "12 (Noon)\n"
#~ "13 (1pm)\n"
#~ "14 (2pm)\n"
#~ "15 (3pm)\n"
#~ "16 (4pm)\n"
#~ "17 (5pm)\n"
#~ "18 (6pm)\n"
#~ "19 (7pm)\n"
#~ "20 (8pm)\n"
#~ "21 (9pm)\n"
#~ "22 (10pm)\n"
#~ "23 (11pm)"
#~ msgstr ""
#~ "0\n"
#~ "1\n"
#~ "2\n"
#~ "3\n"
#~ "4\n"
#~ "5\n"
#~ "6\n"
#~ "7\n"
#~ "8\n"
#~ "9\n"
#~ "10\n"
#~ "11\n"
#~ "12\n"
#~ "13\n"
#~ "14\n"
#~ "15\n"
#~ "16\n"
#~ "17\n"
#~ "18\n"
#~ "19\n"
#~ "20\n"
#~ "21\n"
#~ "22\n"
#~ "23"

#~ msgid "fwbackups Initializing..."
#~ msgstr "Initialisiere fwbackups..."

#~ msgid "<span size=\"xx-large\" weight=\"bold\">fwbackups</span>"
#~ msgstr "<span size=\"xx-large\" weight=\"bold\">fwbackups</span>"

#~ msgid "<span size=\"small\">Please wait while fwbackups initializes.</span>"
#~ msgstr ""
#~ "<span size=\"small\">Bitte warte, während fwbackups initialisiert.</span>"
