# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Alexander Kazancev <kazancas@gmail.com>, 2011
# AlexL <loginov.alex.valer@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: fwbackups\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-01-07 01:37-0800\n"
"PO-Revision-Date: 2017-09-22 11:45+0000\n"
"Last-Translator: AlexL <loginov.alex.valer@gmail.com>\n"
"Language-Team: Russian (http://www.transifex.com/Magic/fwbackups/language/"
"ru/)\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || "
"(n%100>=11 && n%100<=14)? 2 : 3);\n"

#: data/com.diffingo.fwbackups.desktop.in:3 fwbackups/ui/gtk/main.ui:22
#: fwbackups/ui/__init__.py:71
msgid "fwbackups"
msgstr "fwbackups"

#: data/com.diffingo.fwbackups.desktop.in:4
msgid "Backup or restore your files"
msgstr ""

#: data/com.diffingo.fwbackups.desktop.in:6
msgid "backup;archive;archiving;"
msgstr ""

#: data/com.diffingo.fwbackups.metainfo.xml.in:7 fwbackups/ui/__init__.py:848
#, fuzzy
msgid "A feature-rich user backup program"
msgstr "Программа для резервного копирования с продвинутыми возможностями"

#: fwbackups/ui/gtk/BugReport.ui:69
msgid "<span size=\"larger\" weight=\"bold\">Sorry!</span>"
msgstr "<span size=\"larger\" weight=\"bold\">Извините!</span>"

#: fwbackups/ui/gtk/BugReport.ui:81
msgid ""
"fwbackups has run into an unexpected error. You may continue using the "
"program, however it is recommended you quit and open fwbackups again."
msgstr ""
"fwbackups запустился с неустановленной ошибкой. Вы можете продолжить "
"использование программы, но мы рекомендуем закрыть её и попробовать "
"запустить снова."

#: fwbackups/ui/gtk/BugReport.ui:117
msgid "_Details"
msgstr "_Подробности"

#: fwbackups/ui/gtk/backupset.ui:11
msgid "Configure Set"
msgstr "Настроить набор"

#: fwbackups/ui/gtk/backupset.ui:174
msgid "Paths"
msgstr "Пути"

#: fwbackups/ui/gtk/backupset.ui:203
msgid "Destination Type:"
msgstr "Тип назначения:"

#: fwbackups/ui/gtk/backupset.ui:267 fwbackups/ui/gtk/backupset.ui:326
#: fwbackups/ui/gtk/main.ui:600 fwbackups/ui/gtk/main.ui:685
#: fwbackups/ui/gtk/restore.ui:202
msgid "Folder:"
msgstr "Папка:"

#: fwbackups/ui/gtk/backupset.ui:294 fwbackups/ui/gtk/main.ui:628
msgid "/folder"
msgstr "/папка"

#: fwbackups/ui/gtk/backupset.ui:337 fwbackups/ui/gtk/main.ui:649
#: fwbackups/ui/gtk/restore.ui:275
msgid "Host:"
msgstr "Сервер:"

#: fwbackups/ui/gtk/backupset.ui:349 fwbackups/ui/gtk/main.ui:661
#: fwbackups/ui/gtk/restore.ui:287
msgid "Username:"
msgstr "Имя пользователя:"

#: fwbackups/ui/gtk/backupset.ui:361 fwbackups/ui/gtk/main.ui:673
#: fwbackups/ui/gtk/restore.ui:299
msgid "Password:"
msgstr "Пароль:"

#: fwbackups/ui/gtk/backupset.ui:378 fwbackups/ui/gtk/main.ui:701
msgid "_Test Settings"
msgstr "_Тест настроек"

#: fwbackups/ui/gtk/backupset.ui:401 fwbackups/ui/gtk/main.ui:725
#: fwbackups/ui/gtk/restore.ui:364
msgid "Hide password"
msgstr "Скрыть пароль"

#: fwbackups/ui/gtk/backupset.ui:449 fwbackups/ui/gtk/main.ui:783
#: fwbackups/ui/gtk/restore.ui:400
msgid "Port:"
msgstr "Порт:"

#: fwbackups/ui/gtk/backupset.ui:500
msgid "Destination"
msgstr "Назначение"

#: fwbackups/ui/gtk/backupset.ui:527
#, fuzzy
msgid ""
"Use the same syntax a crontab does to enter your settings. To obtain "
"examples and more information on crontab syntax, click 'Help'."
msgstr ""
"Используйте похожий синтаксис crontab при вводе ваших настроек.\n"
"<i>Чтобы посмотреть примеры синтаксиса crontab нажмите 'Справка'.</i>"

#: fwbackups/ui/gtk/backupset.ui:620
#, fuzzy
msgid ""
"No field verification is performed on a manual field to test if the input is "
"valid. Please make sure there are no errors."
msgstr ""
"При ручном вводе не предусмотрена проверка на правильность заполнения "
"полей.\n"
"Убедитесь, что у вас нет ошибок."

#: fwbackups/ui/gtk/backupset.ui:687
msgid "Manual Configuration"
msgstr "Ручная настройка"

#: fwbackups/ui/gtk/backupset.ui:718
msgid "All Months"
msgstr "Весь месяц"

#: fwbackups/ui/gtk/backupset.ui:730
msgid "Only during:"
msgstr "Только в течении:"

#: fwbackups/ui/gtk/backupset.ui:741 fwbackups/ui/gtk/backupset.ui:901
msgid "From:"
msgstr "С:"

#: fwbackups/ui/gtk/backupset.ui:806 fwbackups/ui/gtk/backupset.ui:958
msgid "To:"
msgstr "До:"

#: fwbackups/ui/gtk/backupset.ui:851
msgid "<b>Months</b>"
msgstr "<b>Месяцы</b>"

#: fwbackups/ui/gtk/backupset.ui:877
msgid "Only on:"
msgstr "Только в:"

#: fwbackups/ui/gtk/backupset.ui:889
msgid "All days of the week"
msgstr "Все дни недели"

#: fwbackups/ui/gtk/backupset.ui:998
msgid "<b>Days of the week</b>"
msgstr "<b>Дни недели</b>"

#: fwbackups/ui/gtk/backupset.ui:1024
msgid "At:"
msgstr "В:"

#: fwbackups/ui/gtk/backupset.ui:1035
msgid "All Hours"
msgstr "Каждый час"

#: fwbackups/ui/gtk/backupset.ui:1087
msgid "<b>Hours</b>"
msgstr "<b>Часы</b>"

#: fwbackups/ui/gtk/backupset.ui:1111
msgid "Only at:"
msgstr "Только в:"

#: fwbackups/ui/gtk/backupset.ui:1122
msgid "All Minutes"
msgstr "Каждую минуту"

#: fwbackups/ui/gtk/backupset.ui:1153
msgid "<b>Minute</b>"
msgstr "<b>Минута</b>"

#: fwbackups/ui/gtk/backupset.ui:1171
msgid "Easy Configuration"
msgstr "Быстрая настройка"

#: fwbackups/ui/gtk/backupset.ui:1185
#, fuzzy
msgid ""
"Your backup will run whenever <b>all</b> of the criteria below match the "
"system time and date."
msgstr ""
"<i>Совет: Резервирование будет запущено при <b>каждом</b> совпадении "
"параметров даты и времени системы.</i>"

#: fwbackups/ui/gtk/backupset.ui:1210
msgid "Times"
msgstr "Время"

#: fwbackups/ui/gtk/backupset.ui:1236 fwbackups/ui/gtk/main.ui:856
msgid "Archive (files and folders are packed into a tar archive)"
msgstr "Архив (файлы и папки будут запакованы в tar архив)"

#: fwbackups/ui/gtk/backupset.ui:1250 fwbackups/ui/gtk/main.ui:870
msgid "Direct copy of the files and folders"
msgstr "Прямое копирование файлов и папок"

#: fwbackups/ui/gtk/backupset.ui:1276 fwbackups/ui/gtk/main.ui:888
msgid "Compress archive using"
msgstr "Упаковать в архив используя"

#: fwbackups/ui/gtk/backupset.ui:1303
msgid "Backups are incremental"
msgstr "Использовать нарастающее резервирование"

#: fwbackups/ui/gtk/backupset.ui:1320 fwbackups/ui/gtk/main.ui:913
msgid "<b>Backup Format</b>"
msgstr "<b>Формат резервирования</b>"

#: fwbackups/ui/gtk/backupset.ui:1339
msgid "Set is enabled"
msgstr "Набор включен"

#: fwbackups/ui/gtk/backupset.ui:1351
msgid "Include subfolders"
msgstr "Включая вложенные папки"

#: fwbackups/ui/gtk/backupset.ui:1364 fwbackups/ui/gtk/main.ui:971
msgid "Print disk geometry information to a file"
msgstr "Вывод геометрии диска в файл"

#: fwbackups/ui/gtk/backupset.ui:1377 fwbackups/ui/gtk/main.ui:958
msgid "Print installed packages to a text file"
msgstr "Вывод установленных пакетов в файл"

#: fwbackups/ui/gtk/backupset.ui:1389 fwbackups/ui/gtk/main.ui:983
msgid "Include hidden files"
msgstr "Включая скрытые файлы"

#: fwbackups/ui/gtk/backupset.ui:1401 fwbackups/ui/gtk/main.ui:995
msgid "Handle sparse files efficiently"
msgstr "Эффективная поддержка разреженных файлов"

#: fwbackups/ui/gtk/backupset.ui:1412 fwbackups/ui/gtk/main.ui:1006
msgid "Follow links"
msgstr "Следовать по ссылкам"

#: fwbackups/ui/gtk/backupset.ui:1425 fwbackups/ui/gtk/backupset.ui:1485
#: fwbackups/ui/gtk/main.ui:1019
msgid "<b>Backup Options</b>"
msgstr "<b>Параметры резервирования</b>"

#: fwbackups/ui/gtk/backupset.ui:1442
msgid "Number of old backups to keep:"
msgstr "Число сохраняемых старых резервных копий:"

#: fwbackups/ui/gtk/backupset.ui:1471
#, fuzzy
msgid ""
"A value of  '0' makes a new backup always replace an older one. This option "
"is unavailable with incremental backups."
msgstr ""
"<i>Совет: </i>0<i> будет заменять старые резервные копии новыми.\n"
"Этот параметр неприменим при инкрементном резервировании.</i>"

#: fwbackups/ui/gtk/backupset.ui:1507
msgid "Options (Simple)"
msgstr "Основные опции"

#: fwbackups/ui/gtk/backupset.ui:1557
msgid "Command to run before backup:"
msgstr "Команда для запуска перед резервированием:"

#: fwbackups/ui/gtk/backupset.ui:1568
msgid "Command to run after backup:"
msgstr "Команда для запуска после  резервирования:"

#: fwbackups/ui/gtk/backupset.ui:1579 fwbackups/ui/gtk/main.ui:1083
msgid "Nice value of backup process:"
msgstr "Значение nice для процесса резервирования:"

#: fwbackups/ui/gtk/backupset.ui:1590
msgid ""
"Exclude from backup:\n"
" (newline separated)"
msgstr ""
"Исключить из копии:\n"
"(новый пункт в новой строке)"

#: fwbackups/ui/gtk/backupset.ui:1636
#, fuzzy
msgid ""
"The following tokens may be used in the commands:\n"
"[destination], [set], [date], [backup], [remote_host], [remote_port], "
"[remote_username], [remote_password]\n"
"\n"
"For a description of each, see the user manual."
msgstr ""
"<i>Совет: Следующие маркеры могут быть использованы в командах:\n"
"[destination], [set], [date], [backup], [remote_host], [remote_port], "
"[remote_username], [remote_password]\n"
"\n"
"По описанию каждого смотрите руководство пользователя.</i>"

#: fwbackups/ui/gtk/backupset.ui:1666
msgid "Options (Advanced)"
msgstr "Дополнительные опции"

#: fwbackups/ui/gtk/backupset.ui:1695
msgid "<b>Name:</b>"
msgstr "<b>Имя:</b>"

#: fwbackups/ui/gtk/confirm_dia.ui:36 fwbackups/ui/gtk/error_dia.ui:36
#: fwbackups/ui/gtk/info_dia.ui:35 fwbackups/ui/gtk/warning_dia.ui:39
msgid ""
"<span size=\"larger\" weight=\"bold\">Primary text</span>\n"
"\n"
"Secondary text"
msgstr ""
"<span size=\"larger\" weight=\"bold\">Основной текст</span>\n"
"\n"
"Дополнительный текст"

#: fwbackups/ui/gtk/confirm_dia.ui:49 fwbackups/ui/gtk/info_dia.ui:47
#: fwbackups/ui/gtk/warning_dia.ui:52
msgid "Don't show me this message again"
msgstr "Не показывать больше это сообщение"

#: fwbackups/ui/gtk/export_dia.ui:10 fwbackups/ui/__init__.py:692
msgid "Export Sets"
msgstr "Экспорт наборов"

#: fwbackups/ui/gtk/export_dia.ui:44
msgid "<span size=\"larger\" weight=\"bold\">Export Sets</span>"
msgstr "<span weight=\"bold\" size=\"larger\">Экспорт наборов</span>"

#: fwbackups/ui/gtk/export_dia.ui:57
msgid "Select the set you would like to export."
msgstr "Выбор наборов для экспорта."

#: fwbackups/ui/gtk/export_dia.ui:96
msgid "_Export"
msgstr "_Экспорт"

#: fwbackups/ui/gtk/main.ui:63
msgid "To start, click one of the buttons on the above or use the menus."
msgstr "Для запуска нажмите на указанные кнопки или используйте меню."

#: fwbackups/ui/gtk/main.ui:74
#, fuzzy
msgid ""
"Please do not forget to check your fwbackups log regularly to be informed "
"about any errors and/or failed backup runs."
msgstr ""
"Не забывайте регулярно проверять журнал fwbackups на предмет наличия "
"сообщений\n"
"об ошибках и/или сбоях резервирования."

#: fwbackups/ui/gtk/main.ui:88
msgid "<b>Welcome</b>"
msgstr "<b>Добро пожаловать</b>"

#: fwbackups/ui/gtk/main.ui:113 fwbackups/ui/gtk/main.ui:124
msgid "<i>Not Loaded</i>"
msgstr "<i>Не загружен</i>"

#: fwbackups/ui/gtk/main.ui:136
msgid "Total backup sets:"
msgstr "Всего наборов резервирования:"

#: fwbackups/ui/gtk/main.ui:147
msgid "Failed backup runs:"
msgstr "Ошибка запуска резервирования:"

#: fwbackups/ui/gtk/main.ui:162
msgid "<b>Status</b>"
msgstr "<b>Статус</b>"

#: fwbackups/ui/gtk/main.ui:181
msgid "Overview"
msgstr "Обзор"

#: fwbackups/ui/gtk/main.ui:376 fwbackups/ui/gtk/main.ui:1119
#: fwbackups/ui/gtk/restore.ui:581
msgid "Status:"
msgstr "Статус:"

#: fwbackups/ui/gtk/main.ui:386 fwbackups/ui/gtk/main.ui:1130
msgid "Backup progress:"
msgstr "Прогресс резервирования:"

#: fwbackups/ui/gtk/main.ui:400
#, fuzzy
msgid "Backups Sets"
msgstr "Наборы"

#: fwbackups/ui/gtk/main.ui:820
msgid "Destination type:"
msgstr "Тип назначения:"

#: fwbackups/ui/gtk/main.ui:932
msgid "Enabled"
msgstr "Включен"

#: fwbackups/ui/gtk/main.ui:945
msgid "Recursive"
msgstr "Рекурсивно"

#: fwbackups/ui/gtk/main.ui:1071
#, fuzzy
msgid "Exclude from backup (newline separated):"
msgstr ""
"Исключить из копии:\n"
"(новый пункт в новой строке)"

#: fwbackups/ui/gtk/main.ui:1095
msgid "<b>Advanced Options</b>"
msgstr "<b>Дополнительно</b>"

#: fwbackups/ui/gtk/main.ui:1170 fwbackups/ui/gtk/restore.ui:592
msgid "%s"
msgstr "%s"

#: fwbackups/ui/gtk/main.ui:1266
msgid "One-Time Backup"
msgstr "Разовая копия"

#: fwbackups/ui/gtk/main.ui:1342
msgid "_Save to File"
msgstr "_Сохранить в файл"

#: fwbackups/ui/gtk/main.ui:1390
msgid "Log Viewer"
msgstr "Журнал"

#: fwbackups/ui/gtk/main.ui:1524
msgid "Restore"
msgstr "Восстановить"

#: fwbackups/ui/gtk/preferences.ui:29
#, fuzzy
msgid "Enable debug log messages"
msgstr "Предыдущие сообщения журнала"

#: fwbackups/ui/gtk/preferences.ui:75
#, fuzzy
msgid "Override temporary directory:"
msgstr "Настроить временную папку"

#: fwbackups/ui/gtk/preferences.ui:94
#, fuzzy
msgid "Enable notifications"
msgstr "Отображать уведомления"

#: fwbackups/ui/gtk/preferences.ui:107
#, fuzzy
msgid "<b>Options</b>"
msgstr "<b>Параметры сист. лотка</b>"

#: fwbackups/ui/gtk/preferences.ui:141
msgid "Click to reset \"Don't show me again\" messages"
msgstr "Нажмите для сброса сообщения \"Больше не показывать\""

#: fwbackups/ui/gtk/preferences.ui:174
msgid "Preferences"
msgstr "Параметры"

#: fwbackups/ui/gtk/restore.ui:63
msgid "Set:"
msgstr "Набор:"

#: fwbackups/ui/gtk/restore.ui:73
msgid "Date:"
msgstr "Дата:"

#: fwbackups/ui/gtk/restore.ui:147
msgid "Archive:"
msgstr "Архив:"

#: fwbackups/ui/gtk/restore.ui:242
msgid "/"
msgstr "/"

#: fwbackups/ui/gtk/restore.ui:311
msgid "Location:"
msgstr "Расположение:"

#: fwbackups/ui/gtk/restore.ui:326
msgid "Test Settings"
msgstr "Тест настроек"

#: fwbackups/ui/gtk/restore.ui:349
#, fuzzy
msgid ""
"Note: fwbackups will copy the remote backup to the disk first, then unpack "
"it. Please ensure enough disk space is available."
msgstr ""
"<i>Примечание: fwbackups скопирует сначала удалённую резервную копию на "
"диск, а затем разархивирует её.\n"
"Убедитесь, что у вас достаточно места.</i>"

#: fwbackups/ui/gtk/restore.ui:449
msgid "Source type:"
msgstr "Тип источника:"

#: fwbackups/ui/gtk/restore.ui:461
msgid "Restore to:"
msgstr "Восстановить в:"

#: fwbackups/ui/gtk/restore.ui:514
#, fuzzy
msgid ""
"Tip: entering '/' or selecting 'File System' will restore files to their "
"original locations."
msgstr ""
"<i>Совет: ввод '/' или выбор </i>'Файловая система'<i> восстановит файлы в "
"их изначальное расположение.</i>"

#: fwbackups/ui/gtk/restore.ui:540
msgid "Restore Progress:"
msgstr "Прогресс восстановления:"

#: fwbackups/ui/gtk/restore.ui:658
msgid "_Finish"
msgstr "_Готово"

#: fwbackups/ui/gtk/restore.ui:671
msgid "Restore Files"
msgstr "Восстановление файлов"

#: fwbackups/config.py:58
#, python-format
msgid "Could not create configuration folder `%s':"
msgstr "Не возможно создать папку конфигурации `%s':"

#: fwbackups/config.py:65
#, python-format
msgid "You do not have read and write permissions on folder `%s'."
msgstr "У вас нет прав на чтение/запись папки `%s'."

#: fwbackups/config.py:125
#, python-format
msgid "Key %s of is not a dictionary of options"
msgstr "Ключ %s не в словаре вариантов"

#: fwbackups/config.py:341
#, python-format
msgid "Set '%s' failed to pass section validation"
msgstr "Набор '%s'  не прошёл проверку секции"

#: fwbackups/config.py:344
#, python-format
msgid "'%(a)s' is not a set configuration file."
msgstr "'%(a)s' не является файлом конфигурации набора."

#: fwbackups/config.py:348
#, python-format
msgid ""
"Configuration section 'General' in the set configuration '%s' failed to "
"validate"
msgstr "Секция 'General' в файле конфигурации набора '%s' не прошла проверку"

#: fwbackups/config.py:351
#, python-format
msgid ""
"Configuration section 'Times' in the set configuration '%s' failed to "
"validate"
msgstr "Секция 'Time' в файле конфигурации набора '%s' не прошла проверку"

#: fwbackups/config.py:364
#, python-format
msgid "Unknown option key '%(a)s' present in set configuration '%(b)s'"
msgstr "Неизвестный ключ '%(a)s' в конфигурации набора  '%(b)s'"

#: fwbackups/config.py:369
#, python-format
msgid ""
"Configuration section 'Options' in set configuration '%(a)s' failed to "
"validate: Missing options '%(b)s'"
msgstr ""
"Секция 'Options' в файле конфигурации набора '%(a)s' не прошла проверку: "
"Пропущен параметр  '%(b)s'"

#: fwbackups/config.py:504
msgid "One-time configuration failed to pass section validation"
msgstr "Разовое резервирование не прошло проверку раздела"

#: fwbackups/config.py:507
#, python-format
msgid "'%(a)s' is not a one-time configuration file."
msgstr "'%(a)s' не является файлом конфигурации разового резервирования"

#: fwbackups/config.py:511
msgid ""
"Configuration section 'General' in the one-time configuration file failed to "
"validate"
msgstr ""
"Секция 'General' файла конфигурации разового резервирования не прошла "
"проверку"

#: fwbackups/config.py:523
#, python-format
msgid "Unknown option key '%s' present in one-time backup configuration file"
msgstr "Неверный параметр '%s'  в файле конфигурации разового резервирования"

#: fwbackups/config.py:528
#, python-format
msgid ""
"Configuration section 'Options' in the one-time backup configuration file "
"failed to validate: Missing options '%s'"
msgstr ""
"Секция 'Options' файла конфигурации разового резервирования не прошла "
"проверку: Отсутствует параметр '%s'"

#: fwbackups/config.py:632
msgid "Restore configuration failed to pass section validation"
msgstr "Конфигурация восстановления не прошла проверку секции"

#: fwbackups/config.py:635
#, python-format
msgid "'%(a)s' is not a restore configuration file."
msgstr "'%(a)s' не является файлом конфигурации восстановления"

#: fwbackups/config.py:639
msgid ""
"Configuration section 'General' in the restore configuration file failed to "
"validate"
msgstr "Секция 'General' файла конфигурации восстановления не прошла проверку"

#: fwbackups/config.py:649
#, python-format
msgid "Unknown option key '%s' present in restore configuration file"
msgstr "Неизвестный ключ '%s' в файле конфигурации восстановления"

#: fwbackups/config.py:654
#, python-format
msgid ""
"Configuration section 'Options' in the restore configuration file failed to "
"validate: Missing options '%s'"
msgstr ""
"Секция 'Options' файла конфигурации восстановления не прошла проверку: "
"Пропущен параметр '%s'"

#: fwbackups/config.py:738
msgid "Preferences failed to pass section validation"
msgstr "Файл настроек не прошел проверку секции"

#: fwbackups/config.py:741
#, fuzzy, python-brace-format
msgid "'{constants.PREFSLOC}' is not a fwbackups preferences file."
msgstr "'%(a)s' не является файлом настроек fwbackups."

#: fwbackups/config.py:745
msgid ""
"Configuration section 'General' in the preferences file failed to validate"
msgstr "Секция 'General' файла настроек не прошла проверку"

#: fwbackups/config.py:755
#, python-format
msgid "Unknown option key '%s' present in preferences file"
msgstr "Неизвестный ключ '%s' обнаружен в файле настроек"

#: fwbackups/config.py:760
#, python-format
msgid ""
"Configuration section 'Options' in the preferences file failed to validate: "
"Missing options '%s'"
msgstr ""
"Секция 'Options' файла настроек не прошла проверку: Пропущен параметр '%s'"

#: fwbackups/fwlogger.py:73
#, python-format
msgid "Could not set up the logger: %s"
msgstr "Невозможно настроить журналирование: %s"

#: fwbackups/operations/__init__.py:62
msgid "Canceling the current operation!"
msgstr "Отменяется текущая операция!"

#: fwbackups/operations/__init__.py:66
#, python-format
msgid "Stopping process with ID %s"
msgstr "Остановка процесса с ID %s"

#: fwbackups/operations/__init__.py:69
#, fuzzy, python-format
msgid "Could not stop process %s: %s"
msgstr "Невозможно остановить процесс %(a)s: %(b)s"

#: fwbackups/operations/__init__.py:77
msgid "The operation has been cancelled."
msgstr "Операция была отменена."

#: fwbackups/operations/__init__.py:90
#, python-format
msgid "Error handling file `%s'"
msgstr "Ошибка обработки файла `%s'"

#: fwbackups/operations/__init__.py:91
#, python-format
msgid ""
"Output:\n"
"%s"
msgstr ""
"Вывод:\n"
"%s"

#: fwbackups/operations/__init__.py:96
#, python-format
msgid "Destination folder `%s' exists"
msgstr "Папка назначения `%s'  уже существует"

#: fwbackups/operations/__init__.py:101
#, python-format
msgid "Created destination folder `%s'"
msgstr "Создана папка назначения `%s'"

#: fwbackups/operations/__init__.py:103
#, python-format
msgid "The destination folder `%(a)s' could not be created: %(b)s"
msgstr "Папка назначения `%(a)s' не может быть создана: %(b)s"

#: fwbackups/operations/__init__.py:107
#, python-format
msgid ""
"You do not have read and write permissions on the destination `%s' - if you "
"backed up system files, this operation may fail."
msgstr ""
"У вас нет прав на чтение/запись в назначении `%s - если вы выполните "
"резервное копирование системных файлов, то эта операция может завершиться "
"неудачей."

#: fwbackups/operations/backup.py:86
msgid "rpm - Package list"
msgstr "rpm - список пакетов"

#: fwbackups/operations/backup.py:105
msgid "Pacman - Package list"
msgstr "Pacman - список пакетов"

#: fwbackups/operations/backup.py:111
msgid "dpkg - Package list"
msgstr "dpkg - список пакетов"

#: fwbackups/operations/backup.py:121
msgid "Disk Information"
msgstr "Сведения о диске"

#: fwbackups/operations/backup.py:189
#, python-format
msgid "Attempting to connect to server %s..."
msgstr "Попытка соединения с сервером %s..."

#: fwbackups/operations/backup.py:200
msgid "Attempt to connect succeeded."
msgstr "Соединение прошло успешно."

#: fwbackups/operations/backup.py:203
msgid ""
"The backup destination was either not found or it cannot be written to due "
"to insufficient permissions."
msgstr ""
"Назначение для резервирования либо не было найдено, либо не может быть "
"записано из-за недостаточных прав."

#: fwbackups/operations/backup.py:207 fwbackups/operations/restore.py:93
msgid ""
"A connection was established, but authentication failed. Please verify the "
"username and password and try again."
msgstr ""
"Соединение установлено, но аутенфикация не прошла. Проверьте имя "
"пользователя и пароль."

#: fwbackups/operations/backup.py:212 fwbackups/operations/restore.py:98
#, python-format
msgid ""
"A connection to the server could not be established.\n"
"Error %(a)s: %(b)s"
msgstr ""
"Соединение с сервером не может быть выполнено.\n"
"Ошибка %(a)s: %(b)s"

#: fwbackups/operations/backup.py:217 fwbackups/operations/restore.py:103
msgid ""
"A connection to the server has timed out. Please verify your settings and "
"try again."
msgstr ""
"Соединение с сервером достигло таймаута. Пожалуйста, проверьте ваши "
"настройки и попробуйте снова."

#: fwbackups/operations/backup.py:221 fwbackups/operations/restore.py:107
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s"
msgstr "Соединение с сервером не установлено из-за ошибки: %s"

#: fwbackups/operations/backup.py:239 fwbackups/operations/backup.py:277
#: fwbackups/operations/backup.py:320
#, python-format
msgid ""
"Using %s on Windows: Cancel function will only take effect after a path has "
"been completed."
msgstr ""
"Используйте %s в Windows: Функция отмены будет иметь эффект только после "
"завершения пути."

#. let's deal with real paths
#: fwbackups/operations/backup.py:245 fwbackups/operations/backup.py:283
#: fwbackups/operations/backup.py:293 fwbackups/operations/backup.py:326
#: fwbackups/operations/backup.py:336 fwbackups/operations/backup.py:372
#: fwbackups/operations/backup.py:384
#, python-format
msgid "Backing up path %(a)i/%(b)i: %(c)s"
msgstr "Резервировать путь %(a)i/%(b)i: %(c)s"

#: fwbackups/operations/backup.py:253
#, python-format
msgid "Running command: nice -n %(a)i %(b)s '%(c)s'"
msgstr "Запуск команды: nice -n %(a)i %(b)s '%(c)s'"

#: fwbackups/operations/backup.py:256 fwbackups/operations/backup.py:298
#: fwbackups/operations/backup.py:341 fwbackups/operations/backup.py:391
#: fwbackups/operations/backup.py:598
#, python-format
msgid "Starting subprocess with PID %s"
msgstr "Запуск подпроцесса с PID %s"

#: fwbackups/operations/backup.py:267 fwbackups/operations/backup.py:310
#: fwbackups/operations/backup.py:353 fwbackups/operations/backup.py:403
#, python-format
msgid "Subprocess with PID %(a)s exited with status %(b)s"
msgstr "Подпроцесс с PID %(a)s завершился со статусом %(b)s"

#: fwbackups/operations/backup.py:272 fwbackups/operations/backup.py:315
#: fwbackups/operations/backup.py:358 fwbackups/operations/backup.py:409
#: fwbackups/operations/backup.py:613
#, python-format
msgid "Process exited with status %(a)s. Errors: %(b)s"
msgstr "Процесс завершен со статусом %(a)s. Ошибка: %(b)s"

#: fwbackups/operations/backup.py:285 fwbackups/operations/backup.py:328
#, python-format
msgid "Adding path `%s' to the archive"
msgstr "Добавление пути `%s' в архив"

#: fwbackups/operations/backup.py:292 fwbackups/operations/backup.py:335
#, python-format
msgid ""
"Using %s: Must backup all paths at once - Progress notification will be "
"disabled."
msgstr ""
"Используйте %s: Должно зарезервировать все пути за раз - вывод прогресса "
"операции отключен."

#: fwbackups/operations/backup.py:294 fwbackups/operations/backup.py:337
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s"
msgstr "Запуск команды: nice -n %(a)i %(b)s %(c)s"

#: fwbackups/operations/backup.py:374
#, python-format
msgid ""
"Path %s is missing or cannot be read and will be excluded from the backup."
msgstr ""
"Путь %s отсутствует или не может быть прочитан и будет исключен из "
"резервирования."

#: fwbackups/operations/backup.py:388
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s '%(d)s'"
msgstr "Запуск команды: nice -n %(a)i %(b)s %(c)s '%(d)s'"

#: fwbackups/operations/backup.py:415
msgid "Sending files to server via SFTP"
msgstr "Посылка файлов на сервер через SFTP"

#: fwbackups/operations/backup.py:425
msgid "Could not send file(s) or folder to server:"
msgstr "Невозможно послать файл(ы) или папку на сервер:"

#: fwbackups/operations/backup.py:439
msgid "This function is designed to be subclassed"
msgstr "Эта функция спроектирована как подкласс"

#: fwbackups/operations/backup.py:450
msgid "Starting one-time backup operation"
msgstr "Запуск разового резервирования"

#. fmt: Backup-SetName from Backup-Setname-2009-03-22_20-46[.tar[.gz|.bz2]]
#: fwbackups/operations/backup.py:455 fwbackups/operations/backup.py:527
#: fwbackups/operations/backup.py:625 fwbackups/ui/__init__.py:1501
#: fwbackups/ui/__init__.py:1564 fwbackups/ui/__init__.py:1566
msgid "Backup"
msgstr "Резервная копия"

#: fwbackups/operations/backup.py:455
msgid "OneTime"
msgstr "Разовое"

#: fwbackups/operations/backup.py:469 fwbackups/operations/backup.py:674
msgid "There are no paths to backup!"
msgstr "Нет путей для резервирования!"

#: fwbackups/operations/backup.py:487 fwbackups/operations/backup.py:689
#, python-format
msgid "`%s' exists and will be overwritten."
msgstr "`%s' существует и будет перезаписан."

#. might be ntfs
#. All done!
#: fwbackups/operations/backup.py:508
msgid "Finished one-time backup"
msgstr "Завершено разовое резервирование"

#. Execute the command
#: fwbackups/operations/backup.py:595
#, python-format
msgid "Executing '%s' command"
msgstr "Выполнение команды '%s'"

#: fwbackups/operations/backup.py:612
msgid "Command returned with a non-zero exit status!"
msgstr "Команда вернула ненулевой статус завершения!"

#: fwbackups/operations/backup.py:633
#, python-format
msgid "Removing old backup `%(a)s' on %(b)s"
msgstr "Удаление старой резервной копии: `%(a)s' на %(b)s"

#: fwbackups/operations/backup.py:640 fwbackups/operations/backup.py:653
#, python-format
msgid "Removing old backup `%s'"
msgstr "Удаление старой резервной копии `%s'"

#. oldIncrementalBackup = rsync
#: fwbackups/operations/backup.py:646
#, python-format
msgid "Moving  `%s' to `%s'"
msgstr "Перемещение `%s' в `%s'"

#. source = is not a rsync backup - remove it and start fresh
#: fwbackups/operations/backup.py:649
#, python-format
msgid "`%s' is not an rsync backup - removing."
msgstr "`%s' не является резервной копией rsync - удаляем."

#: fwbackups/operations/backup.py:662
#, python-format
msgid "Starting automatic backup operation of set `%s'"
msgstr "Запуск автоматического резервирования для набора `%s'"

#: fwbackups/operations/backup.py:727 fwbackups/ui/__init__.py:2277
#: fwbackups/ui/__init__.py:2435
msgid "There was an error while performing the backup!"
msgstr "Ошибка при выполнении резервирования!"

#. All done!
#: fwbackups/operations/backup.py:739
#, python-format
msgid "Finished automatic backup operation of set '%s'"
msgstr "Завершено автоматическое резервирование для набора '%s'"

#: fwbackups/operations/restore.py:47
msgid "Starting restore operation"
msgstr "Старт операции восстановления"

#. check if server settings are OK
#: fwbackups/operations/restore.py:76
msgid "Attempting to connect to server"
msgstr "Попытка соединения с сервером"

#: fwbackups/operations/restore.py:89
msgid ""
"The restore source was either not found or it cannot be read due to "
"insufficient permissions."
msgstr ""
"Восстанавливаемый источник либо не был найден, либо не может быть прочитан "
"из-за недостаточных прав."

#: fwbackups/operations/restore.py:121
msgid "Receiving files from server"
msgstr "Приём файлов с сервера"

#: fwbackups/operations/restore.py:132
#, python-format
msgid "Could not receive file from server: %s"
msgstr "Невозможно принять файлы с сервера: %s"

#. We are dealing with a remote folder - our job here is done
#. Either that or an error was encountered above
#. All done!
#: fwbackups/operations/restore.py:137 fwbackups/operations/restore.py:182
msgid "Finished restore operation"
msgstr "Операция восстановления закончена"

#. oops, something is up
#: fwbackups/operations/restore.py:149
#, python-format
msgid "Source `%s' is not a file or folder!"
msgstr "Источник `%s' не файл или папка!"

#. oops, something is up
#: fwbackups/operations/restore.py:158
#, python-format
msgid "Source `%s' is not an archive!"
msgstr "Источник `%s' не архив!"

#: fwbackups/operations/restore.py:162
#, python-format
msgid "Source `%s' is not a folder"
msgstr "Источник `%s' не папка"

#: fwbackups/operations/restore.py:178
#, python-format
msgid "Traceback: %s"
msgstr "Traceback: %s"

#: fwbackups/sftp.py:226
#, python-format
msgid "`%s' is not a file, folder or link! Skipping."
msgstr "`%s' это не файл, папка или ссылка! Пропускается."

#: fwbackups/sftp.py:231
msgid "Could not copy some files due to errors:"
msgstr "Невозможно скопировать некоторые файлы из-за ошибки:"

#: fwbackups/shutil_modded.py:136
#, python-format
msgid "`%s' isn't a file, folder or link! Skipping."
msgstr "`%s' это не файл, папка или ссылка! Пропускается."

#: fwbackups/shutil_modded.py:147
msgid "Couldn't copy some files due to errors:"
msgstr "Невозможно скопировать некоторые файлы из-за ошибки:"

#: fwbackups/ui/__init__.py:226
#, fuzzy, python-format
msgid "<b>Welcome</b>, %s"
msgstr "<b>Добро пожаловать</b>"

#. done in main3Refresh() #self.ui.main3DestinationTypeCombobox.set_active(0)
#. Default Labels...
#: fwbackups/ui/__init__.py:229 fwbackups/ui/__init__.py:1193
#: fwbackups/ui/__init__.py:1298 fwbackups/ui/__init__.py:1680
msgid "Idle"
msgstr "Ожидание"

#. Default progressbars...
#: fwbackups/ui/__init__.py:234 fwbackups/ui/__init__.py:1192
msgid "Click 'Backup Set Now' to begin"
msgstr "Нажмите 'Резервировать сейчас' для начала"

#: fwbackups/ui/__init__.py:235
msgid "Click 'Start Backup' to begin"
msgstr "Нажмите \"Запуск резервирования\" для начала"

#: fwbackups/ui/__init__.py:236
msgid "Click 'Start Restore' to begin"
msgstr "Нажмите 'Старт восстановления' для начала"

#: fwbackups/ui/__init__.py:263
msgid "Could not setup the fwbackups configuration folder"
msgstr "Невозможно задать папку настроек fwbackups"

#: fwbackups/ui/__init__.py:264 fwbackups/ui/__init__.py:302
#, python-format
msgid "The following error occured: %s"
msgstr "Произошла следующая ошибка: %s"

#: fwbackups/ui/__init__.py:271
#, python-format
msgid "Validation error: %s"
msgstr "Ошибка проверки: %s"

#: fwbackups/ui/__init__.py:272
msgid "Preferences could not be read"
msgstr "Невозможно прочитать настройки"

#: fwbackups/ui/__init__.py:272
msgid ""
"The preferences file may be corrupted and could not be read by fwbackups. "
"Would you like to initialize a new one from the default values? If not, "
"fwbackups will exit."
msgstr ""
"Файл настроек может быть повреждён или недоступен для чтения fwbackups. Вы "
"хотите создать новый с настройками по умолчанию? Если нет, то fwbackups "
"завершит работу."

#: fwbackups/ui/__init__.py:301
msgid "Could not setup the logger"
msgstr "Невозможно настроить журналирование"

#: fwbackups/ui/__init__.py:325
msgid "Previous installation of fwbackups 1.42.x or older detected"
msgstr "Обнаружена предыдущая (1.42) или более старая версия fwbackups."

#: fwbackups/ui/__init__.py:325
msgid ""
"Because of certain major changes in fwbackups, your configuration must be "
"imported manually. To do this, run fwbackups as the root user and select "
"<i>File > Import</i> from the menu to import your old configuration.\n"
"If this action is not completed, the backups from version 1.42.x <b>will not "
"run automatically</b>.\n"
"<i>Tip: The 1.42.x configuration was stored in /etc/fwbackups</i>."
msgstr ""
"Из-за некоторых серьезных изменений в fwbackups, ваша конфигурация должна "
"быть импортированы вручную. Для этого надо запустить fwbackups от root "
"выбрать <i> Файл > Импорт </i> из меню, чтобы импортировать ваши старые "
"настройки.\n"
"Если не сделать это, то резервные копии с версии 1.42.x <b>не будут "
"запускаться автоматически </b>.\n"
"<i>Совет: Конфигурация версии 1.42.x хранится в файле /etc/fwbackups</i>."

#: fwbackups/ui/__init__.py:332
msgid "A backup of /etc/crontab could not be created"
msgstr "Резервная копия /etc/crontab не может быть создана"

#: fwbackups/ui/__init__.py:332
msgid ""
"You may wish to edit /etc/crontab manually and remove any fwbackups-related "
"lines."
msgstr ""
"Вы можете отредактировать etc/crontab и удалить строки, относящиеся к "
"fwbackups."

#: fwbackups/ui/__init__.py:333
msgid "Could not create a backup of /etc/crontab; refusing to clean up."
msgstr "Невозможно создать резервную копию  /etc/crontab; требуется очистка."

#: fwbackups/ui/__init__.py:336
msgid "Cleaning up /etc/crontab from previous installation of fwbackups"
msgstr "Очистка /etc/crontab от предыдущей установки fwbackups"

#: fwbackups/ui/__init__.py:345
#, python-format
msgid ""
"fwbackups was unable to clean up the system crontab: %s. You may wish to "
"edit /etc/crontab manually and remove any fwbackups-related lines."
msgstr ""
"fwbackups не может очистить системный crontab: %s. Вы можете отредактировать "
"etc/crontab и удалить строки, относящиеся к fwbackups."

#: fwbackups/ui/__init__.py:346
msgid "Cleanup of the system crontab failed"
msgstr "Cбой очистки системного crontab"

#: fwbackups/ui/__init__.py:351
msgid "fwbackups administrator started"
msgstr "Запуск управления fwbackups"

#: fwbackups/ui/__init__.py:360
msgid "Would you like to clean up the log file?"
msgstr "Вы хотите очистить файл журнала?"

#: fwbackups/ui/__init__.py:360
#, python-format
msgid ""
"The log file is becoming large (%s). Would you like to clear it? This will "
"permanently remove all entries from the log."
msgstr ""
"Файл журнала становится слишком большим (%s). Не хотите его очистить? Это "
"уничтожит все записи в журнале."

#: fwbackups/ui/__init__.py:478
msgid "Regenerating crontab"
msgstr "Регенерация crontab"

#: fwbackups/ui/__init__.py:479
msgid "Please wait... Regenerating crontab"
msgstr "Подождите... Идет регенерация crontab"

#: fwbackups/ui/__init__.py:492
#, python-format
msgid "Could not parse the configuration for set '%s'"
msgstr "Невозможно прочитать конфигурацию для набора '%s'"

#: fwbackups/ui/__init__.py:493
#, python-format
msgid ""
"The set configuration file '%s' failed to validate, so it may not be "
"properly scheduled. Other sets are unaffected by this error."
msgstr ""
"Файл конфигурации набора '%s'  не прошёл проверку, и поэтому не может быть "
"верно повторён по расписанию. Другие настройки должны помочь обойти ошибку."

#: fwbackups/ui/__init__.py:500
#, python-format
msgid ""
"Internal error: generated entry for set '%s' was not parsable. Please submit "
"a bug report."
msgstr ""
"Внутренняя ошибка: сгенерированная запись для набора '%s' не разбираема. "
"Отправьте сообщение об ошибке."

#: fwbackups/ui/__init__.py:503
#, python-format
msgid "Could not schedule automated backups for set '%s'"
msgstr ""
"Невозможно создать расписание автоматического резервирования для набора '%s'"

#: fwbackups/ui/__init__.py:504
msgid ""
"fwbackups could not regenerate a crontab entry because an error occured:\n"
msgstr "fwbackups не может регенерировать запись crontab из-за ошибки:\n"

#: fwbackups/ui/__init__.py:505
#, python-format
msgid ""
"%(a)s\n"
"\n"
"The crontab entry associated with the error was:\n"
"%(b)s"
msgstr ""
"%(a)s\n"
"\n"
"Запись crontab, ассоциированная с ошибкой, следующая:\n"
"%(b)s"

#. After all is done, log an message
#: fwbackups/ui/__init__.py:508
#, python-format
msgid "Saving set `%s' to the crontab"
msgstr "Запись набора `%s' в crontab"

#: fwbackups/ui/__init__.py:520
#, python-format
msgid "Unable to write new crontab: %s"
msgstr "Не могу записать новую задачу crontab: %s"

#: fwbackups/ui/__init__.py:521
#, fuzzy
msgid "Error saving backup schedule to crontab"
msgstr "Невозможно записать расписание резервирования в crontab"

#: fwbackups/ui/__init__.py:521
msgid ""
"Changes made to the backup schedule may not have been correctly saved. If "
"you are using custom cron entry for a backup set, verify the values are "
"valid.\n"
"\n"
msgstr ""

#: fwbackups/ui/__init__.py:525
msgid ""
"A backup of the crontab was restored; the latest changes to the backup "
"schedule not have been saved."
msgstr ""
"Резервная копия crontab восстановлена; последние изменения в расписание "
"резервного копирования не были сохранены."

#: fwbackups/ui/__init__.py:527
#, fuzzy, python-brace-format
msgid "A backup of the crontab could not be restored: {error}"
msgstr "Резервная копия crontab не может быть восстановлена"

#: fwbackups/ui/__init__.py:533
msgid "fwbackups is working"
msgstr "fwbackups работает"

#: fwbackups/ui/__init__.py:534
msgid ""
"An operation is currently in progress. Would you like to cancel it and quit "
"anyways?"
msgstr "Операция всё ещё выполняется. Вы хотите её прервать и выйти?"

#: fwbackups/ui/__init__.py:536
msgid "Please wait... Canceling operations"
msgstr "Подождите... Операция отменяется"

#: fwbackups/ui/__init__.py:549
msgid "fwbackups detected more than one alive threads!"
msgstr "fwbackups обнаружил более одного живого потока!"

#: fwbackups/ui/__init__.py:554
#, python-format
msgid "Closed dead Paramiko thread: %s"
msgstr "Закрыт умерший поток Paramiko: %s"

#. FIXME: Figure out how to kill other thread types. For now, just log.
#: fwbackups/ui/__init__.py:557
#, python-format
msgid "Could not close thread %s!"
msgstr "Невозможно закрыть поток %s!"

#: fwbackups/ui/__init__.py:558
msgid "Please submit a bug report and include this message."
msgstr "Отправьте сообщение об ошибке, включив в него данный текст."

#: fwbackups/ui/__init__.py:567 fwbackups/ui/__init__.py:2192
msgid "Could not save backup schedule"
msgstr "Не удалось сохранить расписание резервирования"

#: fwbackups/ui/__init__.py:567
msgid ""
"fwbackups was unable to save the backup scheduling information to the "
"crontab. If you are using manual times entry in one of your sets, please "
"verify that all five fields are using the correct syntax."
msgstr ""
"fwbackups не может записать расписание резервирования в crontab. Если вы "
"используете ручное задание времени в одном из ваших наборов, убедитесь в "
"правильном синтаксисе задания."

#. Shutdown logging & quit the GTK mainloop
#: fwbackups/ui/__init__.py:569
msgid "fwbackups administrator closed"
msgstr "Управление fwbackups закрыто"

#: fwbackups/ui/__init__.py:580
msgid "Creating thread"
msgstr "Создаётся поток"

#: fwbackups/ui/__init__.py:581
msgid "testConnection(): Creating thread"
msgstr "testConnection(): Создание потока"

#: fwbackups/ui/__init__.py:584
msgid "Attempting to connect"
msgstr "Попытка соединения"

#: fwbackups/ui/__init__.py:588
#, python-format
msgid "testConnection(): Thread returning with retval %s"
msgstr "testConnection(): Поток вернул значение %s"

#: fwbackups/ui/__init__.py:590
msgid "Success!"
msgstr "Успешно!"

#: fwbackups/ui/__init__.py:590
#, python-format
msgid "fwbackups was able to connect and authenticate on '%s'."
msgstr "fwbackups успешно подключился и авторизовался на '%s'."

#: fwbackups/ui/__init__.py:592
msgid "Remote destination is not usable"
msgstr "Удалённое назначение не может использоваться"

#: fwbackups/ui/__init__.py:592
#, python-format
msgid ""
"The folder '%(a)s' on '%(b)s' either does not exist or it is not a folder. "
"Please verify your settings and try again."
msgstr ""
"Папка '%(a)s' на '%(b)s' не существует или не является папкой. Проверьте "
"настройки и попробуйте снова."

#: fwbackups/ui/__init__.py:594 fwbackups/ui/__init__.py:1469
msgid "Authentication failed"
msgstr "Сбой аутентификации"

#: fwbackups/ui/__init__.py:594
#, python-format
msgid ""
"A connection to '%s' was established, but authentication failed. Please "
"verify the username and password and try again."
msgstr ""
"Соединение с '%s' установлено, но аутенфикация не прошла. Проверьте имя "
"пользователя и пароль."

#: fwbackups/ui/__init__.py:596 fwbackups/ui/__init__.py:600
#, python-format
msgid "A connection to '%s' could not be established"
msgstr "Соединение с '%s' не может быть установлено"

#: fwbackups/ui/__init__.py:596
#, python-format
msgid "Error %(a)s: %(b)s"
msgstr "Ошибка %(a)s: %(b)s"

#: fwbackups/ui/__init__.py:598
#, python-format
msgid "The server '%s' is not responding"
msgstr "Сервер  '%s' не отвечает"

#: fwbackups/ui/__init__.py:598 fwbackups/ui/__init__.py:1476
msgid "Please verify your settings and try again."
msgstr "Проверьте параметры и повторите ещё раз."

#: fwbackups/ui/__init__.py:600
#, python-format
msgid "Error: %s. Please verify your settings and try again."
msgstr "Ошибка: %s. Проверьте ваши настройки и попробуйте снова."

#: fwbackups/ui/__init__.py:602 fwbackups/ui/__init__.py:1168
#: fwbackups/ui/__init__.py:1481
msgid "Unexpected error"
msgstr "Произошла непредвиденная ошибка"

#: fwbackups/ui/__init__.py:602
#, fuzzy
msgid "An unknown error occurred while testing for connectivity."
msgstr "Ошибка при импорте gtk/gobject."

#: fwbackups/ui/__init__.py:615 fwbackups/ui/__init__.py:618
#: fwbackups/ui/__init__.py:903 fwbackups/widgets.py:619
#: fwbackups/widgets.py:622
msgid "Choose file(s)"
msgstr "Выберите файл(ы)"

#: fwbackups/ui/__init__.py:617 fwbackups/ui/__init__.py:699
#: fwbackups/ui/__init__.py:905 fwbackups/ui/__init__.py:975
#: fwbackups/ui/__init__.py:1334 fwbackups/ui/__init__.py:1694
#: fwbackups/ui/__init__.py:1708 fwbackups/ui/__init__.py:1722
#: fwbackups/widgets.py:621 fwbackups/widgets.py:633
msgid "_Open"
msgstr ""

#: fwbackups/ui/__init__.py:617 fwbackups/ui/__init__.py:699
#: fwbackups/ui/__init__.py:905 fwbackups/ui/__init__.py:975
#: fwbackups/ui/__init__.py:1334 fwbackups/ui/__init__.py:1694
#: fwbackups/ui/__init__.py:1708 fwbackups/ui/__init__.py:1722
#: fwbackups/widgets.py:621 fwbackups/widgets.py:633 fwbackups/widgets.py:740
#, fuzzy
msgid "_Cancel"
msgstr "Отмена..."

#: fwbackups/ui/__init__.py:619
msgid "Configuration files (*.conf)"
msgstr "Файлы конфигурации (*.conf)"

#: fwbackups/ui/__init__.py:680
msgid "File Exists"
msgstr "Файл уже существует"

#: fwbackups/ui/__init__.py:681
#, python-format
msgid "'%s.conf' already exists! Would you like to overwrite it?"
msgstr "'%s.conf' уже существует. Заменить его?"

#: fwbackups/ui/__init__.py:687
#, python-format
msgid "Exported set `%(a)s' to `%(b)s'"
msgstr "Экспортирован набор `%(a)s' в `%(b)s"

#: fwbackups/ui/__init__.py:697 fwbackups/ui/__init__.py:700
#: fwbackups/ui/__init__.py:906 fwbackups/ui/__init__.py:973
#: fwbackups/ui/__init__.py:976 fwbackups/ui/__init__.py:1332
#: fwbackups/ui/__init__.py:1335 fwbackups/widgets.py:631
#: fwbackups/widgets.py:634
msgid "Choose folder(s)"
msgstr "Выберите папку(и)"

#: fwbackups/ui/__init__.py:707
msgid "Sets exported"
msgstr "Наборы экспортированы"

#: fwbackups/ui/__init__.py:707
msgid "The selected sets were exported successfully."
msgstr "Выбранные потоки успешно экспортированы."

#: fwbackups/ui/__init__.py:734 fwbackups/ui/__init__.py:1119
#: fwbackups/ui/__init__.py:1136 fwbackups/ui/__init__.py:1210
#: fwbackups/ui/__init__.py:2247
msgid "No set has been selected"
msgstr "Нет выбранных наборов"

#: fwbackups/ui/__init__.py:734
msgid "You must select a set to duplicate."
msgstr "Вы должны выбрать набор для дублирования."

#: fwbackups/ui/__init__.py:738
msgid "_copy"
msgstr "_копирование"

#: fwbackups/ui/__init__.py:892
#, python-format
msgid "Resetting preference '%(a)s' to 0"
msgstr "Сброс настройки  '%(a)s' в 0"

#: fwbackups/ui/__init__.py:993 fwbackups/ui/__init__.py:1256
#: fwbackups/ui/__init__.py:1261 fwbackups/ui/__init__.py:1352
#: fwbackups/ui/__init__.py:1535 fwbackups/ui/__init__.py:1610
#: fwbackups/ui/__init__.py:1647 fwbackups/ui/__init__.py:2152
#: fwbackups/ui/__init__.py:2157
msgid "Missing information"
msgstr "Отсутствует информация"

#: fwbackups/ui/__init__.py:993
msgid "Please complete the host, username, folder and port fields."
msgstr "Задайте сервер, имя пользователя, папку и порт."

#: fwbackups/ui/__init__.py:1119
msgid "You must select a set to edit."
msgstr "Вы должны выбрать набор для редактирования."

#: fwbackups/ui/__init__.py:1136
msgid "You must select a set to remove."
msgstr "Вы должны выбрать набор для удаления."

#: fwbackups/ui/__init__.py:1138
#, python-format
msgid "Delete backup set '%s'?"
msgstr "Удалить набор резервирования '%s'?"

#: fwbackups/ui/__init__.py:1138
#, fuzzy
msgid ""
"This action will permanently delete the backup set configuration. This "
"action will not delete any existing backups, or files and folders associated "
"with the set."
msgstr ""
"Это действие полностью удалит настройку набора резервирования, но не "
"затронет существующих резервных копий или файлов."

#: fwbackups/ui/__init__.py:1145 fwbackups/ui/__init__.py:1153
#, python-format
msgid ""
"An error occured while removing set `%(a)s':\n"
"%(b)s"
msgstr ""
"Ошибка при удалении набора `%(a)s':\n"
"%(b)s"

#: fwbackups/ui/__init__.py:1146
#, python-format
msgid "Could not remove backup set '%s'"
msgstr "Невозможно удалить набор резервирования '%s'"

#: fwbackups/ui/__init__.py:1154
#, python-format
msgid "Could not remove the automated backup schedule for set '%s'"
msgstr ""
"Не могу удалить расписание автоматического резервирования для набора '%s'"

#: fwbackups/ui/__init__.py:1158
#, python-format
msgid "Removing set `%s'"
msgstr "Удаление набора `%s'"

#: fwbackups/ui/__init__.py:1168
#, python-format
msgid ""
"An unexpected error occured while attempting to obtain the selected set:\n"
"%s"
msgstr ""
"Произошла непредвиденная ошибка при попытке получить выбранный набор:\n"
"%s"

#: fwbackups/ui/__init__.py:1210
msgid "You must select a set to restore."
msgstr "Вы должны выбрать набор для восстановления."

#: fwbackups/ui/__init__.py:1256 fwbackups/ui/__init__.py:2152
msgid "Please fill in the Folder field."
msgstr "Заполните поле Папка."

#: fwbackups/ui/__init__.py:1261 fwbackups/ui/__init__.py:2157
msgid "Please fill in the Host, Username, Port and Folder fields."
msgstr "Задайте сервер, имя пользователя, папку и порт."

#: fwbackups/ui/__init__.py:1352 fwbackups/ui/__init__.py:1535
#: fwbackups/ui/__init__.py:1647
msgid "Please complete all of the host, username, folder and port fields."
msgstr "Задайте все поля: сервер, имя пользователя, папку и порт."

#: fwbackups/ui/__init__.py:1376
msgid "Log cleared"
msgstr "Журнал очищен"

#: fwbackups/ui/__init__.py:1381
msgid "Clear the old log entries?"
msgstr "Удалить старые записи журнала?"

#: fwbackups/ui/__init__.py:1382
msgid "This action will permanently remove all log entries."
msgstr "Это действие полностью удалит все записи журнала."

#: fwbackups/ui/__init__.py:1400
#, python-format
msgid "Log saved to file `%s'"
msgstr "Журнал записан в файл '%s'"

#: fwbackups/ui/__init__.py:1466
msgid "Previous backups could not be found"
msgstr "Невозможно найти предыдущую резервную копию"

#: fwbackups/ui/__init__.py:1467
#, python-format
msgid "The destination folder for set '%s' was not found."
msgstr "Папка назначения для набора '%s' не найдена."

#: fwbackups/ui/__init__.py:1470
#, python-format
msgid ""
"fwbackups was unable to authenticate on the remote server. Please verify the "
"username and password for set '%s' and try again."
msgstr ""
"fwbackups не может аутенфицироваться на удалённом сервере. Проверьте имя "
"пользователя и пароль для набора '%s' и попробуйте снова."

#: fwbackups/ui/__init__.py:1472 fwbackups/ui/__init__.py:1478
msgid "Connection failed"
msgstr "Сбой подключения"

#: fwbackups/ui/__init__.py:1473
#, python-format
msgid ""
"A connection to the server could not be established:\n"
"Error %(a)s: %(b)s\n"
"Please verify your settings and try again."
msgstr ""
"Соединение с сервером не установлено:\n"
"Ошибка %(a)s: %(b)s\n"
" Проверьте ваши настройки и попробуйте снова."

#: fwbackups/ui/__init__.py:1475
msgid "Remote server is not responding"
msgstr "Удалённый сервер не доступен"

#: fwbackups/ui/__init__.py:1479
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s\n"
"Please verify your settings and try again."
msgstr ""
"Соединение с сервером не установлено из-за ошибки: %s\n"
"Проверьте ваши настройки и попробуйте снова."

#: fwbackups/ui/__init__.py:1493
#, python-format
msgid ""
"Error obtaining file listing in destination %(a)s:\n"
"%(b)s"
msgstr ""
"Ошибка получения списка файлов в назначении %(a)s:\n"
"%(b)s"

#: fwbackups/ui/__init__.py:1494
#, python-format
msgid "Could not get a list of old backups for set '%s'"
msgstr "Невозможно получить список старых резервных копий для набора '%s'"

#: fwbackups/ui/__init__.py:1494
msgid ""
"If the destination is on removable media such as an external hard disk, "
"please attach it and try again."
msgstr ""
"Если назначение является съёмным носителем, таким как внешний жёсткий диск, "
"подключите его и попробуйте снова."

#. We can't start a restore if there are no set dates
#: fwbackups/ui/__init__.py:1504 fwbackups/ui/__init__.py:1618
#: fwbackups/ui/__init__.py:1619
msgid "No backups found"
msgstr "Не найдено резервных копий"

#: fwbackups/ui/__init__.py:1610
msgid "Please select a backup date."
msgstr "Выберите дату резервирования."

#: fwbackups/ui/__init__.py:1619
#, python-format
msgid ""
"The backup set '%s' does not have any stored backups yet! Choose another "
"set, or alternatively choose a different restore source."
msgstr ""
"Набор восстановления '%s'  не имеет сохранённых копий. Выберите другой набор "
"или другой источник восстановления."

#: fwbackups/ui/__init__.py:1626 fwbackups/ui/__init__.py:1637
msgid "Restore source"
msgstr "Восстановить источник"

#: fwbackups/ui/__init__.py:1626
msgid "Please enter the location of the local archive."
msgstr "Задайте расположение локального архива."

#: fwbackups/ui/__init__.py:1629
msgid "Wrong file type"
msgstr "Неверный тип файла"

#: fwbackups/ui/__init__.py:1630
msgid ""
"The file you selected is not a supported archive.\n"
"Supported archives types are tar with no, gzip or bzip2 compression."
msgstr ""
"Файл, выбранный вами, не является поддерживаемым архивом.\n"
"Типы поддерживаемых архивов: tar без сжатия, gzip или bzip2 сжатие."

#: fwbackups/ui/__init__.py:1637
msgid "Please enter the location of the local folder."
msgstr "Задайте расположение локальной папки."

#: fwbackups/ui/__init__.py:1692 fwbackups/ui/__init__.py:1695
#: fwbackups/ui/__init__.py:1706 fwbackups/ui/__init__.py:1709
#: fwbackups/ui/__init__.py:1720 fwbackups/ui/__init__.py:1723
msgid "Select a Folder"
msgstr "Выбор папки"

#: fwbackups/ui/__init__.py:1737 fwbackups/ui/__init__.py:1740
msgid "Invalid set name"
msgstr "Неверное имя набора"

#: fwbackups/ui/__init__.py:1737
msgid "Please enter a set name."
msgstr "Введите имя набора."

#: fwbackups/ui/__init__.py:1740
msgid ""
"'temporary_name' is a reserved name. Please choose another name for the set."
msgstr ""
"'temporary_name' - это зарезервированное имя. Выберите другое имя для набора."

#: fwbackups/ui/__init__.py:1744
#, python-format
msgid "Overwrite settings for set '%s'?"
msgstr "Перезаписать настройки для набора '%s'?"

#: fwbackups/ui/__init__.py:1745
msgid ""
"This will overwrite the stored settings with the current ones. Are you sure "
"you want to continue?"
msgstr ""
"Это действие перезапишет сохранённые настройки на текущие. Вы хотите "
"продолжить?"

#: fwbackups/ui/__init__.py:1856
msgid "Error parsing configuration file"
msgstr "Ошибка разбора файла конфигурации"

#: fwbackups/ui/__init__.py:1857
msgid "fwbackups will using the default times instead."
msgstr "fwbackups будет использовать время по умолчанию."

#: fwbackups/ui/__init__.py:1870
#, python-format
msgid "Unknown destination type `%s'"
msgstr "Неизвестный тип назначения `%s'"

#: fwbackups/ui/__init__.py:2072
msgid "Error creating the automated backup schedules"
msgstr "Ошибка создания расписания автоматического резервирования"

#: fwbackups/ui/__init__.py:2073
#, python-format
msgid ""
"The crontab could not be written because an error occured:\n"
"%s"
msgstr ""
"Сrontab не может быть записан из-за ошибки:\n"
"%s"

#: fwbackups/ui/__init__.py:2108 fwbackups/widgets.py:712
msgid "Parsing configuration files"
msgstr "Разбор файла конфигурации"

#: fwbackups/ui/__init__.py:2123 fwbackups/widgets.py:718
#, python-format
msgid "Refusing to parse file `%s': configuration files must end in `.conf'"
msgstr ""
"Сбой разбора файла `%s': файл конфигурации должен иметь расширение `.conf'"

#: fwbackups/ui/__init__.py:2175
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s"
msgstr "Переименовать набор `%(a)s' в `%(b)s"

#: fwbackups/ui/__init__.py:2177
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s failed: %(c)s"
msgstr "Переименование набора `%(a)s' в `%(b)s не удалось: %(c)s"

#: fwbackups/ui/__init__.py:2178
#, python-format
msgid "Could not rename set '%(a)s' to '%(b)s'"
msgstr "Невозможно переименовать набор '%(a)s' в '%(b)s'"

#. creating a set
#: fwbackups/ui/__init__.py:2184
#, python-format
msgid "Creating set `%s'"
msgstr "Создаётся набор `%s'"

#. editing a set
#: fwbackups/ui/__init__.py:2188
#, python-format
msgid "Saving changes to set `%s'"
msgstr "Запись изменений в набор `%s'"

#: fwbackups/ui/__init__.py:2192
msgid ""
"Your set configuration changes were saved, but fwbackups was unable to save "
"the backup scheduling information to the crontab. If you are using manual "
"times entry, please verify that all five fields are using the correct syntax."
msgstr ""
"Изменение настроек вашего набора были сохранены, но fwbackups не смог "
"сохранить расписание резервирования в crontab. Если вы используете ручное "
"задание времени, проверьте, чтобы все поля имели верный синтаксис."

#: fwbackups/ui/__init__.py:2230 fwbackups/ui/__init__.py:2391
#, python-format
msgid "[%(a)i/%(b)i] Backing up: %(c)s"
msgstr "[%(a)i/%(b)i] Резервирование: %(c)s"

#: fwbackups/ui/__init__.py:2233 fwbackups/ui/__init__.py:2394
#, python-format
msgid "[%(a)i/%(b)i] Backing up files... Please wait"
msgstr "[%(a)i/%(b)i] Резервируются файлы... Подождите"

#: fwbackups/ui/__init__.py:2235 fwbackups/ui/__init__.py:2396
msgid "Cleaning old backups"
msgstr "Очистка старых резервных копий"

#: fwbackups/ui/__init__.py:2237 fwbackups/ui/__init__.py:2398
msgid "Sending files to remote server"
msgstr "Отправка файлов на удалённый сервер"

#: fwbackups/ui/__init__.py:2239 fwbackups/ui/__init__.py:2400
msgid "Executing user command"
msgstr "Выполнение команды пользователя"

#: fwbackups/ui/__init__.py:2247
msgid "You must select to initiate a manual set backup."
msgstr "Вы должны выбрать для начала заданный вручную набор."

#: fwbackups/ui/__init__.py:2253 fwbackups/ui/__init__.py:2409
#: fwbackups/ui/__init__.py:2499
msgid "Initializing"
msgstr "Инициализация"

#: fwbackups/ui/__init__.py:2255 fwbackups/ui/__init__.py:2411
#, fuzzy
msgid "Backup started"
msgstr "Сбой создания резервной копии!"

#: fwbackups/ui/__init__.py:2255
#, python-format
msgid "Starting a set backup operation of '%(a)s'"
msgstr "Запуск операции резервирования для набора '%(a)s'"

#: fwbackups/ui/__init__.py:2258 fwbackups/ui/__init__.py:2316
#: fwbackups/ui/__init__.py:2418 fwbackups/ui/__init__.py:2478
#: fwbackups/ui/__init__.py:2504 fwbackups/ui/__init__.py:2562
msgid "Please wait..."
msgstr "Пожалуйста, подождите..."

#: fwbackups/ui/__init__.py:2264 fwbackups/ui/__init__.py:2422
#: fwbackups/ui/__init__.py:2509
msgid "Working"
msgstr "Работает"

#. thread returned
#: fwbackups/ui/__init__.py:2272 fwbackups/ui/__init__.py:2430
#: fwbackups/ui/__init__.py:2517
#, python-format
msgid "Thread returned with retval %s"
msgstr "Поток вернул ошибку %s"

#. error
#: fwbackups/ui/__init__.py:2281 fwbackups/ui/__init__.py:2299
#: fwbackups/ui/__init__.py:2439 fwbackups/ui/__init__.py:2458
#: fwbackups/ui/__init__.py:2523 fwbackups/ui/__init__.py:2543
msgid "<span color=\"Red\">Error</span>"
msgstr "<span color=\"Red\">Ошибка</span>"

#: fwbackups/ui/__init__.py:2282 fwbackups/ui/__init__.py:2443
#, python-format
msgid "An error occurred while initializing the backup operation: %s"
msgstr "Ошибка при инициализации операции резервирования: %s"

#: fwbackups/ui/__init__.py:2286 fwbackups/ui/__init__.py:2444
msgid "Error initializing backup"
msgstr "Ошибка инициализации резервной копии"

#: fwbackups/ui/__init__.py:2296 fwbackups/ui/__init__.py:2455
#, fuzzy
msgid "Backup complete"
msgstr "Наборы"

#: fwbackups/ui/__init__.py:2296
#, python-format
msgid "Finished the automatic backup operation of set `%(a)s'"
msgstr "Завершено автоматическое резервирование для набора `%(a)s'"

#: fwbackups/ui/__init__.py:2297 fwbackups/ui/__init__.py:2456
#: fwbackups/ui/__init__.py:2540
msgid "<span color=\"dark green\">Operation complete</span>"
msgstr "<span color=\"dark green\">Операция завершена</span>"

#: fwbackups/ui/__init__.py:2301 fwbackups/ui/__init__.py:2460
#, fuzzy
msgid "Error during backup"
msgstr "Ошибка инициализации резервной копии"

#: fwbackups/ui/__init__.py:2301
#, python-format
msgid ""
"An error occured while performing the automatic backup operation of set "
"`%(a)s'"
msgstr ""
"Ошибка при выполнении автоматического резервирования для набора `%(a)s'"

#: fwbackups/ui/__init__.py:2304 fwbackups/ui/__init__.py:2465
#, fuzzy
msgid "Backup cancelled"
msgstr "Сбой создания резервной копии!"

#: fwbackups/ui/__init__.py:2304
#, python-format
msgid "The automatic backup operation of set `%(a)s' was cancelled"
msgstr "Операция автоматического резервирования для набора `%(a)s' отменена"

#: fwbackups/ui/__init__.py:2305 fwbackups/ui/__init__.py:2466
#: fwbackups/ui/__init__.py:2551
msgid "<span color=\"red\">Operation cancelled</span>"
msgstr "<span color=\"red\">Операция отменена</span>"

#: fwbackups/ui/__init__.py:2306 fwbackups/ui/__init__.py:2467
#: fwbackups/ui/__init__.py:2552
msgid "Operation cancelled"
msgstr "Операция была отменена."

#: fwbackups/ui/__init__.py:2317 fwbackups/ui/__init__.py:2479
#: fwbackups/ui/__init__.py:2563
msgid "Cancelling..."
msgstr "Отмена..."

#: fwbackups/ui/__init__.py:2411
msgid "Starting a one-time backup operation"
msgstr "Запуск разового резервирования"

#: fwbackups/ui/__init__.py:2455
msgid "Finished the one-time backup operation"
msgstr "Окончание разового резервирования"

#: fwbackups/ui/__init__.py:2460
msgid "An error occured while performing the one-time backup operation"
msgstr "Ошибка при выполнении операции разового резервирования"

#: fwbackups/ui/__init__.py:2465
msgid "The one-time backup operation was cancelled"
msgstr "Операция разового резервирования была отменена."

#. no "current file" yet
#: fwbackups/ui/__init__.py:2491
msgid "Receiving files from remote server"
msgstr "Приём файлов с удалённого сервера"

#. we have a 'current file'
#: fwbackups/ui/__init__.py:2493
#, python-format
msgid "Restoring: %s"
msgstr "Восстановление: %s"

#: fwbackups/ui/__init__.py:2501
#, fuzzy
msgid "Restore started"
msgstr "Восстановить источник"

#: fwbackups/ui/__init__.py:2501
msgid "Starting a restore operation"
msgstr "Старт операции восстановления"

#: fwbackups/ui/__init__.py:2519
msgid ""
"There was an error while performing the restore! Enable debug messages for "
"more information."
msgstr ""
"Ошибка при выполнении восстановления! Включите сообщения дебаггинга для "
"получения большей информации."

#: fwbackups/ui/__init__.py:2526
#, python-format
msgid "An error occurred while initializing the restore operation: %s"
msgstr "Ошибка при инициализации операции восстановления: %s"

#: fwbackups/ui/__init__.py:2527
msgid "Error initializing restore operation"
msgstr "Ошибка инициализации операции восстановления"

#: fwbackups/ui/__init__.py:2539
#, fuzzy
msgid "Restore finished"
msgstr "Восстановление не удалось!"

#: fwbackups/ui/__init__.py:2539
msgid "Finished the restore operation"
msgstr "Операция восстановления завершена"

#: fwbackups/ui/__init__.py:2545
#, fuzzy
msgid "Error during restore"
msgstr "Ошибка инициализации операции восстановления"

#: fwbackups/ui/__init__.py:2545
msgid "An error occured while performing the restore operation"
msgstr "Ошибка при выполнении операции восстановления"

#: fwbackups/ui/__init__.py:2550
#, fuzzy
msgid "Restore cancelled"
msgstr "Восстановление не удалось!"

#: fwbackups/ui/__init__.py:2550
msgid "The restore operation was cancelled"
msgstr "Операция восстановления была отменена."

#: fwbackups/widgets.py:149 fwbackups/widgets.py:192
msgid "CRITICAL"
msgstr "КРИТИЧНО"

#: fwbackups/widgets.py:149 fwbackups/widgets.py:192
msgid "ERROR"
msgstr "ОШИБКА"

#: fwbackups/widgets.py:151 fwbackups/widgets.py:194
msgid "WARNING"
msgstr "ПРЕДУПРЕЖДЕНИЕ"

#: fwbackups/widgets.py:164 fwbackups/widgets.py:188
msgid "Previous log messages"
msgstr "Предыдущие сообщения журнала"

#: fwbackups/widgets.py:168 fwbackups/widgets.py:201
msgid "No previous log messages to display"
msgstr "Нет сообщений предыдущего журнала для отображения"

#: fwbackups/widgets.py:169 fwbackups/widgets.py:180
msgid "Current session's log messages"
msgstr "Журнал сообщений текущей сессии"

#: fwbackups/widgets.py:536
msgid "Access"
msgstr "Доступ"

#: fwbackups/widgets.py:542
msgid "Path"
msgstr "Путь"

#: fwbackups/widgets.py:658
msgid "Please select a path before choosing an action."
msgstr "Выберите путь перед заданием действия."

#: fwbackups/widgets.py:691
msgid "Export"
msgstr "Экспорт"

#: fwbackups/widgets.py:697
msgid "Set"
msgstr "Набор"

#: fwbackups/widgets.py:732
msgid "Bug Report"
msgstr "Отправить сообщение об ошибке"

#: fwbackups/widgets.py:740
msgid "_Save"
msgstr ""

#~ msgid "*** Initializing files"
#~ msgstr "*** Инициализация файлов"

#, python-format
#~ msgid ""
#~ "Folder %s exists and will be emptied. Press <Enter> to confirm or "
#~ "<ctrl+c> to cancel..."
#~ msgstr ""
#~ "Папка %s существует и должна быть очищена. Нажмите <Enter> для "
#~ "подтверждения или <ctrl+c> для отмены..."

#, python-format
#~ msgid "Cleaning folder %s..."
#~ msgstr "Очистка папки %s..."

#~ msgid "*** Remote settings"
#~ msgstr "*** Удалённые настройки"

#~ msgid "Hostname [localhost]: "
#~ msgstr "Имя хоста [localhost]:"

#~ msgid "Port [22]: "
#~ msgstr "Порт [22]:"

#~ msgid "The port field can only contain numbers. Please try again."
#~ msgstr "Поле Порт может содержать только число. Введите заново."

#, python-format
#~ msgid "Username [%s]: "
#~ msgstr "Имя пользователя [%s]:"

#~ msgid "Password: "
#~ msgstr "Пароль:"

#, python-format
#~ msgid "Remote folder [%s]: "
#~ msgstr "Удалённая папка [%s]:"

#, python-format
#~ msgid "*** Running %(a)s backup with engine %(b)s"
#~ msgstr "*** Запуск %(a)s резервирования на движке %(b)s"

#, python-format
#~ msgid "*** Running restore of remote test backup %s"
#~ msgstr "*** Запуск восстановления внешней тестовой копии %s"

#, python-format
#~ msgid "*** Running restore of local test backup %s"
#~ msgstr "*** Запуск восстановления локальной тестовой копии %s"

#~ msgid "*** Running restore of a local archive"
#~ msgstr "*** Запуск восстановления локального архива"

#~ msgid "*** Running restore of a local folder"
#~ msgstr "*** Запуск восстановления локальной папки"

#~ msgid "*** Running restore of a remote archive (SSH)"
#~ msgstr "*** Запуск восстановления внешнего архива  (SSH)"

#~ msgid "*** Running restore of a remote folder (SSH)"
#~ msgstr "*** Запуск восстановления внешней папки (SSH)"

#, python-format
#~ msgid "Error: %s"
#~ msgstr "Ошибка: %s"

#~ msgid "Run with --help for usage information."
#~ msgstr "Запустите с --help для получения дополнительной информации."

#~ msgid ""
#~ "Usage: fwbackups-run [OPTIONS] Set_Name(s)\n"
#~ "Options:\n"
#~ "  -v, --verbose  :  Increase verbosity (print debug messages)\n"
#~ "  -h, --help  :  Print this message and exit\n"
#~ "  -l, --silent  :  Print messages to log file only\n"
#~ "\n"
#~ "Set_Name(s) is space-seperated list of set names to run backups of."
#~ msgstr ""
#~ "Использование: fwbackups-run [параметры] имена_наборов\n"
#~ "Параметры:\n"
#~ "  -v, --verbose  : Выдать больше информации (печать сообщения дебагинга)\n"
#~ "  -h, --help  :  Напечатать это сообщение и выйти\n"
#~ "  -l, --silent  :  Выводить сообщения только в файл журнала\n"
#~ "\n"
#~ "Имена_наборов представляют собой заданные через пробел наборы для "
#~ "резервирования."

#~ msgid "Invalid usage: Requires at least one set name to backup"
#~ msgstr ""
#~ "Неверное использование: Требуется как минимум одно имя конфигурации для "
#~ "резервирования"

#, python-format
#~ msgid "The set configuration for '%s' was not found - skipping."
#~ msgstr "Настройки набора для '%s' не найдены - пропуск."

#~ msgid "An error occurred while initializing the backup operation!"
#~ msgstr "Ошибка при инициализации операции резервирования!"

#~ msgid ""
#~ "Usage: fwbackups-runonce --destination-type=TYPE --engine=ENGINE "
#~ "[OPTIONS] Path(s) Destination\n"
#~ "Options:\n"
#~ "  -v, --verbose  :  Increase verbosity (print debug messages)\n"
#~ "  -h, --help  :  Print this message and exit\n"
#~ "  -r, --recursive  :  Perform a recursive backup\n"
#~ "  -i, --hidden  :  Include hidden files in the backup\n"
#~ "  -p, --packages2file  :  Print installed package list to a text file\n"
#~ "  -d, --diskinfo2file  :  Print disk geometry to a file (must be root)\n"
#~ "  -s, --sparse  :  Handle sparse files efficiently\n"
#~ "  -e, --engine=ENGINE  :  Use specified backup engine.\n"
#~ "              Valid engines are tar, tar.gz, tar.bz2 and rsync.\n"
#~ "  -x, --exclude='PATTERN'  :  Skip files matching PATTERN.\n"
#~ "  -n, --nice=NICE  :  Indicate the niceness of the backup process (-20 to "
#~ "19)\n"
#~ "  --destination-type=TYPE  :  Destination type (`local' or `remote "
#~ "(ssh)')\n"
#~ "  --remote-host=HOSTNAME  :  Connect to remote host `HOSTNAME'\n"
#~ "  --remote-user=USERNAME  :  Connect as specified username\n"
#~ "  --remote-password=PASSWORD  :  Connect using password `PASSWORD'\n"
#~ "  --remote-port=PORT  :  Connect on specified port (default 22)\n"
#~ "\n"
#~ "Path(s) is space-seperated list of paths to include in the backup.\n"
#~ "Destination is the directory where the OneTime backup should be placed "
#~ "within.\n"
#~ "\n"
#~ "Defaults to tar engine and local destination unless specified otherwise.\n"
#~ "Supplying --remote* will have no effect unless thedestination type is\n"
#~ "`remote (ssh)'."
#~ msgstr ""
#~ "Использование: wbackups-runonce --destination-type=ТИП --engine=ДВИЖОК "
#~ "[ПАРАМЕТРЫ] Путь(Пути) Назначение\n"
#~ "Параметры:\n"
#~ "  -v, --verbose  : Выдать больше информации (печать сообщения дебагинга)\n"
#~ "  -h, --help  :  Напечатать это сообщение и выйти\n"
#~ "  -r, --recursive  :  Выполнить рекурсивное резервирование\n"
#~ "  -i, --hidden  :  Включить в резервную копию скрытые файлы\n"
#~ "  -p, --packages2file  :  Вывести список установленных пакетов в "
#~ "текстовый файл\n"
#~ "  -d, --diskinfo2file  :  Вывести геометрию диска в файл (должны быть "
#~ "права root)\n"
#~ "  -s, --sparse  :  Более эффективно поддерживать разреженные файлы\n"
#~ "  -e, --engine=ДВИЖОК  :  Использовать определенный движок "
#~ "резервирования.\n"
#~ "              Доступны следующие движки: tar, tar.gz, tar.bz2 и rsync.\n"
#~ "  -x, --exclude='МАСКА'  :  Пропустить файлы, совпадающие с  МАСКОЙ.\n"
#~ "  -n, --nice=NICE  :  задать nice для процесса резервирования (от -20 до "
#~ "19)\n"
#~ "  --destination-type=ТИП  :  Тип назначения (`local' или `remote (ssh)')\n"
#~ "  --remote-host=ИМЯ_ХОСТА  : Подключиться к удалённому хосту с именем "
#~ "`ИМЯ_ХОСТА'\n"
#~ "  --remote-user=ИМЯ_ПОЛЬЗОВАТЕЛЯ :  Подключиться под определённым "
#~ "пользователем\n"
#~ "  --remote-password=ПАРОЛЬ : Подключиться с использованием пароля "
#~ "`ПАРОЛЬ\n"
#~ "  --remote-port=PORT  :  Подключиться к заданному порту (по умолчанию "
#~ "22)\n"
#~ "\n"
#~ "Путь(пути) - пути для резервирования через пробел.\n"
#~ "Назначение - папка, где должна быть помещена Одномоментная резервная "
#~ "копия.\n"
#~ "\n"
#~ "По умолчанию в качестве движка используется tar и локальное расположение "
#~ "копии.\n"
#~ "Параметры удалённого сервера не будут применены, пока назначение не будет "
#~ "установлено в\n"
#~ "`remote (ssh)'."

#, python-format
#~ msgid "No such engine `%s'"
#~ msgstr "Нет такого движка: `%s'"

#~ msgid "You must be root to set a niceness below 0"
#~ msgstr "Вы должны иметь права root для nice ниже 0"

#~ msgid "Nice value must be an integer between -20 and 19"
#~ msgstr "Значение nice может быть числом от -20 до 19"

#~ msgid "Requires at least one path to backup and a destination"
#~ msgstr "Требуется как минимум один путь для резервирования и назначение"

#~ msgid "Destination type was not specified"
#~ msgstr "Тип назначения не определён"

#~ msgid "An engine was not specified"
#~ msgstr "Не задан движок"

#~ msgid "Please make sure you have a valid GTK+ Runtime Environment."
#~ msgstr "Убедитесь, что у вас установлена нужная версия GTK+."

#, python-format
#~ msgid "fwbackups bug report written saved at %s"
#~ msgstr "Сообщение об ошибке fwbackups записано как %s"

#~ msgid "Could not write bug report due to insufficient permissions."
#~ msgstr "Невозможно записать сообщение об ошибке из-за недостатка прав."

#~ msgid "Please install pycrypto (python-crypto)"
#~ msgstr "Установите pycrypto (python-crypto)"

#~ msgid "Please install paramiko (python-paramiko)"
#~ msgstr "Установите paramiko (python-paramiko)"

#, python-format
#~ msgid "<span size=\"small\">%s%% complete: %s</span>"
#~ msgstr "<span size=\"small\">%s%% завершено: %s</span>"

#~ msgid "Checking permissions"
#~ msgstr "Проверка прав"

#~ msgid "Setting up the logger and user preferences"
#~ msgstr "Настройка журнала и прав пользователя"

#~ msgid "Populating the log viewer"
#~ msgstr "Заполнение просмотрщика журнала"

#~ msgid ""
#~ "pynotify was not found. Notifcations will not be displayed unless notify-"
#~ "python/pynotify is installed."
#~ msgstr ""
#~ "pynotify не найден. Оповещения не будут отображаться, пока не будет "
#~ "установлен notify-python/pynotify."

#~ msgid "Cleaning after previous versions"
#~ msgstr "Очистка после предыдущей версии"

#~ msgid "Ready!"
#~ msgstr "Готов!"

#, python-format
#~ msgid "Could not create notification: %s"
#~ msgstr "Невозможно создать оповещение: %s"

#~ msgid ""
#~ "There was an error saving the new backup schedule. A backup will be "
#~ "restored, however the changes made to the backup schedule may not have "
#~ "been correctly saved.\n"
#~ "\n"
#~ "If you see this message, please report a bug against fwbackups."
#~ msgstr ""
#~ "Возникла ошибка при сохранении нового расписания резервного копирования. "
#~ "Резервная копия будет восстановлена, однако изменения, сделанные в "
#~ "расписании резервного копирования, могут быть сохранены некорректно.\n"
#~ "\n"
#~ "Если вы видите это сообщение, пожалуйста, сообщите об ошибке в fwbackups."

#~ msgid "Select file(s)"
#~ msgstr "Выберите файл(ы)"

#, python-format
#~ msgid "Could not remove fwbackup's session autostart regkey: %s"
#~ msgstr "Невозможно удалить ключ реестра автозапуска сессии fwbackup  '%s'"

#, python-format
#~ msgid "Could not remove fwbackup's session autostart file: %s"
#~ msgstr "Невозможно удалить файл автозапуска сессии fwbackups '%s'"

#~ msgid "Please enter a Pycron installation directory."
#~ msgstr "Задайте папку установки Pycron."

#~ msgid "Configuration not found"
#~ msgstr "Файл конфигурации не найден"

#~ msgid ""
#~ "The pycron configuration file was not found in the directory entered. "
#~ "Please ensure that pycron is installed in the selected installation "
#~ "folder and that it contains either a pycron configuration file or the "
#~ "sample pycron configuration."
#~ msgstr ""
#~ "Файл конфигурации pycron не был найден в папке входа. Пожалуйста, "
#~ "убедитесь, что pycron установлен в выбранную папку установки, и что он "
#~ "содержит либо конфигурационный файл pycron, либо пример конфигурации "
#~ "pycron."

#~ msgid "Automated restore not supported"
#~ msgstr "Автоматическое восстановление не поддерживается"

#~ msgid ""
#~ "This backup set cannot be automatically restored because restoration of "
#~ "Archive backups has not been implemented for systems with Python 2.4. "
#~ "Please see the user guide for details on manual restoration."
#~ msgstr ""
#~ "Этот набор резервирования не может быть автоматически восстановлен, "
#~ "потому что восстановление из архива не доступно на системах с Python 2.4. "
#~ "Прочитайте руководство пользователя по ручному восстановлению."

#~ msgid "Status"
#~ msgstr "Статус"

#~ msgid "Show this program's version and exit"
#~ msgstr "Вывести версию установленной программы и закончить работу"

#~ msgid "Show this help message and exit"
#~ msgstr "Показать это сообщение и закончить работу"

#~ msgid "print log messages to the terminal. Use this option twice"
#~ msgstr ""
#~ "Вывод сообщений журнала на терминал. Используйте этот параметр дважды"

#~ msgid "start GUI minimized in the system tray"
#~ msgstr "Сворачивать программу в системный лоток"

#~ msgid "[ set by runapp.py ]"
#~ msgstr "[ набор через runapp.py ]"

#~ msgid "<span size=\"large\" weight=\"bold\">Overview</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Обзор</span>"

#~ msgid "_New Set"
#~ msgstr "_Новый набор"

#~ msgid "Ed_it Set"
#~ msgstr "Редактировать набор"

#~ msgid "_Delete Set"
#~ msgstr "Удалить набор"

#~ msgid "_Backup Set Now"
#~ msgstr "_Резервировать сейчас"

#~ msgid "Re_store Set"
#~ msgstr "Восстановить набор"

#~ msgid "<span size=\"large\" weight=\"bold\">Backups Sets</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Наборы резервирования</span>"

#~ msgid "_Add File(s)"
#~ msgstr "_Добавить файл(ы)"

#~ msgid "_Add Folder(s)"
#~ msgstr "_Добавить папку(и)"

#~ msgid ""
#~ "Local folder\n"
#~ "Remote folder (SSH)"
#~ msgstr ""
#~ "Локальная папка\n"
#~ "Удалённая папка (SSH)"

#~ msgid "_Browse..."
#~ msgstr "_Обзор..."

#~ msgid ""
#~ "gzip: fast, lightweight\n"
#~ "bzip2: slower, more efficient"
#~ msgstr ""
#~ "gzip: быстро, не требует ресурсов\n"
#~ "bzip2: медленнее, большее сжатие"

#~ msgid "_Back"
#~ msgstr "_Назад"

#~ msgid "_Next"
#~ msgstr "_Следующий"

#~ msgid "_Start Backup"
#~ msgstr "_Запуск резервирования"

#~ msgid "<span size=\"large\" weight=\"bold\">One-Time Backup</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Разовое резервирование</span>"

#~ msgid "<span size=\"large\" weight=\"bold\">Log Viewer</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Просмотр журнала</span>"

#~ msgid "_File"
#~ msgstr "_Файл"

#~ msgid "Create a new backup set"
#~ msgstr "Создать новый набор резервирования"

#~ msgid "Import a set from a .conf file"
#~ msgstr "Импортировать набор из .conf файла"

#~ msgid "_Import Sets"
#~ msgstr "_Импорт наборов"

#~ msgid "Export one or more sets to .conf files"
#~ msgstr "Экспортировать один или несколько наборов в .conf файл"

#~ msgid "E_xport Sets"
#~ msgstr "_Экспорт наборов"

#~ msgid "_Edit"
#~ msgstr "_Править"

#~ msgid "Edit the selected backup set"
#~ msgstr "Редактировать выбранный набор"

#~ msgid "_Edit Set"
#~ msgstr "_Править набор"

#~ msgid "Remove the selected backup set"
#~ msgstr "Удалить выбранный набор резервирования"

#~ msgid "Duplicate the selected backup set"
#~ msgstr "Скопировать выбранный набор"

#~ msgid "D_uplicate Set"
#~ msgstr "_Дублировать набор"

#~ msgid "_View"
#~ msgstr "_Вид"

#~ msgid "Switch to Overview"
#~ msgstr "Переключиться в Обзор"

#~ msgid "_Overview"
#~ msgstr "_Обзор"

#~ msgid "Switch to User Backup Sets"
#~ msgstr "Переключить в Пользовательский набор резервирования"

#~ msgid "_Backup Sets"
#~ msgstr "_Наборы для резервирования"

#~ msgid "Switch to One-Time Backup"
#~ msgstr "Переключиться на Разовое резервирование"

#~ msgid "O_ne-Time Backup"
#~ msgstr "_Разовое резервирование"

#~ msgid "Switch to Log Viewer"
#~ msgstr "Переключиться в Просмотр журнала"

#~ msgid "_Log"
#~ msgstr "_Журнал"

#~ msgid "Switch to Restore"
#~ msgstr "Переключиться в Восстановление"

#~ msgid "_Restore"
#~ msgstr "_Восстановить"

#~ msgid "_Help"
#~ msgstr "_Справка"

#~ msgid "Check for _Updates"
#~ msgstr "_Проверить обновления"

#~ msgid "About fwbackups"
#~ msgstr "О fwbackups"

#~ msgid ""
#~ "<span color=\"blue\"><u>http://www.diffingo.com/opensource</u></span>"
#~ msgstr ""
#~ "<span color=\"blue\"><u>http://www.diffingo.com/opensource</u></span>"

#~ msgid "<span size=\"small\">(C) 2005 - 2010 Stewart Adam</span>"
#~ msgstr "<span size=\"small\">(C) 2005 - 2010 Stewart Adam</span>"

#, no-c-format
#~ msgid "<span size=\"xx-large\" weight=\"bold\">fwbackups %s</span>"
#~ msgstr "<span size=\"xx-large\" weight=\"bold\">fwbackups %s</span>"

#~ msgid "<span size=\"large\"> A feature-rich user backup program</span>"
#~ msgstr ""
#~ "<span size=\"large\"> Программа резервирования с продвинутыми "
#~ "настройками</span>"

#~ msgid ""
#~ "    This program is free software; you can redistribute it and/or modify\n"
#~ "    it under the terms of the GNU General Public License as published by\n"
#~ "    the Free Software Foundation; either version 2 of the License, or\n"
#~ "    (at your option) any later version.\n"
#~ "\n"
#~ "    This program is distributed in the hope that it will be useful,\n"
#~ "    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
#~ "    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n"
#~ "    See the GNU General Public License for more details.\n"
#~ "\n"
#~ "    You should have received a copy of the GNU General Public License\n"
#~ "    along with this program; if not, write to the\n"
#~ "    Free Software Foundation, Inc.,\n"
#~ "    51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA\n"
#~ msgstr ""
#~ "fwbackup - это свободная программа; вы можете распространять её\n"
#~ "и/или модифицировать в соответствии с лицензией\n"
#~ "GNU General Public License, которая опубликована\n"
#~ "Free Software Foundation; или версией 2 лицензии, или\n"
#~ "(по вашему желанию) любой поздней версией.\n"
#~ "\n"
#~ "fwbackup распространяется в надежде, что она будет полезна,\n"
#~ "но БЕЗ ЛЮБЫХ ГАРАНТИЙ; даже без подразумеваемой гарантии\n"
#~ "КОММЕРЧЕСКОЙ ЦЕННОСТИ или ПРИГОДНОСТИ ДЛЯ КОНКРЕТНЫХ ЦЕЛЕЙ.\n"
#~ "Смотрите GNU General Public License для подробностей.\n"
#~ "\n"
#~ "Вы должны были получить копию GNU General Public License\n"
#~ "с программой; если нет, то напишите в Free Software\n"
#~ "Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, "
#~ "USA\n"

#~ msgid "License"
#~ msgstr "Лицензия"

#~ msgid ""
#~ "\n"
#~ "Developers:\n"
#~ "          Stewart Adam < s.adam@diffingo.com >\n"
#~ "\n"
#~ "Documenters:\n"
#~ "          Stewart Adam < s.adam@diffingo.com >\n"
#~ "\n"
#~ "Translators:\n"
#~ "\tN/A\n"
#~ "\n"
#~ "Graphic Designers:\n"
#~ "\tStewart Adam < s.adam@diffingo.com >\n"
#~ "        * Based on gnome-icon-theme icons\n"
#~ msgstr ""
#~ "\n"
#~ "Разработчики:\n"
#~ "          Stewart Adam < s.adam@diffingo.com >\n"
#~ "\n"
#~ "Документация:\n"
#~ "          Stewart Adam < s.adam@diffingo.com >\n"
#~ "\n"
#~ "Переводчики:\n"
#~ "\tАлександр Казанцев <kazancas@gmail.com>\n"
#~ "        Алексей Логинов <loginov.alex.valer@gmail.com>\n"
#~ "\n"
#~ "Дизайн:\n"
#~ "\tStewart Adam < s.adam@diffingo.com >\n"
#~ "        * Основан на иконках gnome-icon-theme\n"

#~ msgid "Credits"
#~ msgstr "Авторы"

#~ msgid "Select a file or folder"
#~ msgstr "Выбор файла или папки"

#~ msgid "Save to..."
#~ msgstr "Сохранение в..."

#~ msgid "Status: fwbackups is running"
#~ msgstr "Статус: fwbackups запущен"

#~ msgid "_Show Administrator"
#~ msgstr "_Показать окно управления"

#~ msgid "_Minimize to tray on close"
#~ msgstr "_Минимизировать в сист. лоток при закрытии"

#~ msgid "Edit preferences"
#~ msgstr "Редактировать параметры"

#~ msgid "_Preferences"
#~ msgstr "_Параметры"

#~ msgid "_Quit"
#~ msgstr "_Выход"

#~ msgid "Export to:"
#~ msgstr "Экспорт в:"

#~ msgid ""
#~ "Set backup\n"
#~ "Local archive\n"
#~ "Local folder\n"
#~ "Remote archive (SSH)\n"
#~ "Remote folder (SSH)"
#~ msgstr ""
#~ "Набор резервирования\n"
#~ "Локальный архив\n"
#~ "Локальная папка\n"
#~ "Удалённый архив (SSH)\n"
#~ "Удалённая папка (SSH)"

#~ msgid "Browse..."
#~ msgstr "Обзор..."

#~ msgid "Start _Restore"
#~ msgstr "Запуск _восстановления"

#~ msgid "Minimize to tray on close"
#~ msgstr "Сворачивать в системный лоток при закрытии"

#~ msgid "Show notifications in tray area"
#~ msgstr "Показывать уведомления в системном лотке"

#~ msgid "Show tray icon"
#~ msgstr "Показывать иконку в системном лотке"

#~ msgid "Start minimized"
#~ msgstr "Запускать в свёрнутом виде"

#~ msgid "Always show debug messages in the log"
#~ msgstr "Всегда показывать сообщения дебагинга в журнале"

#~ msgid "Start fwbackups (minimized) when I login"
#~ msgstr "Запускать fwbackups (свернув) при каждом входе"

#~ msgid "<b>Misc. Options</b>"
#~ msgstr "<b>Разное</b>"

#~ msgid "Pycron installation directory:"
#~ msgstr "Папка установки pycron:"

#~ msgid "<b>Windows-specific options</b>"
#~ msgstr "<b>Параметры только для ОС Windows</b>"

#~ msgid "<b>Day(s) of the Week</b>"
#~ msgstr "<b>Дни недели</b>"

#~ msgid "<b>Month(s)</b>"
#~ msgstr "<b>Месяц(ы)</b>"

#~ msgid " "
#~ msgstr " "

#~ msgid "<b>Day(s) of Month</b>"
#~ msgstr "<b>Дни месяца</b>"

#~ msgid "<b>Hour(s)</b>"
#~ msgstr "<b>Час(ы)</b>"

#~ msgid "<b>Minute(s)</b>"
#~ msgstr "<b>Минут(ы)</b>"

#~ msgid ""
#~ "January\n"
#~ "February\n"
#~ "March\n"
#~ "April\n"
#~ "May\n"
#~ "June\n"
#~ "July\n"
#~ "August\n"
#~ "September\n"
#~ "October\n"
#~ "November\n"
#~ "December"
#~ msgstr ""
#~ "Январь\n"
#~ "Февраль\n"
#~ "Март\n"
#~ "Апрель\n"
#~ "Май\n"
#~ "Июнь\n"
#~ "Июль\n"
#~ "Август\n"
#~ "Сентябрь\n"
#~ "Октябрь\n"
#~ "Ноябрь\n"
#~ "Декабрь"

#~ msgid ""
#~ "Sunday\n"
#~ "Monday\n"
#~ "Tuesday\n"
#~ "Wednesday\n"
#~ "Thurday\n"
#~ "Friday\n"
#~ "Saturday"
#~ msgstr ""
#~ "Воскресенья\n"
#~ "Понедельника\n"
#~ "Вторника\n"
#~ "Среды\n"
#~ "Четверга\n"
#~ "Пятницы\n"
#~ "Субботы"

#~ msgid ""
#~ "Sundays\n"
#~ "Mondays\n"
#~ "Tuesdays\n"
#~ "Wednesdays\n"
#~ "Thurdays\n"
#~ "Fridays\n"
#~ "Saturdays"
#~ msgstr ""
#~ "Воскресенье\n"
#~ "Понедельник\n"
#~ "Вторник\n"
#~ "Среда\n"
#~ "Четверг\n"
#~ "Пятница\n"
#~ "Суббота"

#~ msgid ""
#~ "0 (12am)\n"
#~ "1 (1am)\n"
#~ "2 (2am)\n"
#~ "3 (3am)\n"
#~ "4 (4am)\n"
#~ "5 (5am)\n"
#~ "6 (6am)\n"
#~ "7 (7am)\n"
#~ "8 (8am)\n"
#~ "9 (9am)\n"
#~ "10 (10am)\n"
#~ "11 (11am)\n"
#~ "12 (Noon)\n"
#~ "13 (1pm)\n"
#~ "14 (2pm)\n"
#~ "15 (3pm)\n"
#~ "16 (4pm)\n"
#~ "17 (5pm)\n"
#~ "18 (6pm)\n"
#~ "19 (7pm)\n"
#~ "20 (8pm)\n"
#~ "21 (9pm)\n"
#~ "22 (10pm)\n"
#~ "23 (11pm)"
#~ msgstr ""
#~ "0\n"
#~ "1\n"
#~ "2\n"
#~ "3\n"
#~ "4\n"
#~ "5\n"
#~ "6\n"
#~ "7\n"
#~ "8\n"
#~ "9\n"
#~ "10\n"
#~ "11\n"
#~ "12\n"
#~ "13\n"
#~ "14\n"
#~ "15\n"
#~ "16\n"
#~ "17\n"
#~ "18\n"
#~ "19\n"
#~ "20\n"
#~ "21\n"
#~ "22\n"
#~ "23"

#~ msgid "fwbackups Initializing..."
#~ msgstr "Инициализация fwbackups..."

#~ msgid "<span size=\"xx-large\" weight=\"bold\">fwbackups</span>"
#~ msgstr "<span size=\"xx-large\" weight=\"bold\">fwbackups</span>"

#~ msgid "<span size=\"small\">Please wait while fwbackups initializes.</span>"
#~ msgstr "<span size=\"small\">Дождитесь инициализации fwbackups.</span>"

#~ msgid "Traceback Here"
#~ msgstr "Здесь Traceback"

#~ msgid "Unable to clean user crontab!"
#~ msgstr "Невозможно очистить crontab пользователя!"

#, python-format
#~ msgid "Could not locate the pycron or the sample pycron configuration in %s"
#~ msgstr "Не обнаружен pycron или пример файла конфигурации pycron в %s"

#, python-format
#~ msgid "Could not locate the pycron or the sample pycron crontab file in %s"
#~ msgstr "Не обнаружен pycron или пример файла pycron crontab в %s"
